### ISSUE TITLE
Island deletion broken

### ISSUE THREAD

**Issue by phit** [DevOnTheRocks/SkyClaims#10]
using beta1
`/isa delete <name>`
http://vpaste.net/SzIpe

~`/is delete`
just says too many arguments~ nvm, that's not even a thing

**Comment by Mohron** [comment]
> phit - Today at 7:58 AM
> http://vpaste.net/3PaHO
> isa delete
> seems to work fine besides this
> database was edited properly
> claim is gone too

Closing since this appears to be fixed.
