### ISSUE TITLE
Not Teleporting On Island

### ISSUE THREAD

**Issue by vortexdecoded** [DevOnTheRocks/SkyClaims#100]
Using sponge version 1.12.2-7.1.2 addon for forge
Using skyclaims version 0.27.2-s7.0-BETA

I expected it to place you on the island upon teleportation, im using a custom island.
but it just drops you into the void

Steps To Reproduce
Create An island, When it Asks If You Want To Teleport You Hit Yes

![2018-10-24_19 38 58](https://user-images.githubusercontent.com/44451560/47467472-7b7ab000-d7c4-11e8-9bf8-5f559698e3d0.png)

 /sponge:callback 1bdd405f-b1d6-4095-affc-cb78d17759bd   is what i got in the logs after i teleported, don't know if it means anything.

an idea you could add is have it search, say for example grass, it could find the closes grass block and teleport you to it or something of the sort

**Comment by phit** [comment]
please read https://devontherocks.github.io/SkyClaims/#/schematics?id=creating-a-schematic

you need to stand in the position where you want the player to spawn when creating the schematic

**Comment by vortexdecoded** [comment]
nvm Thanks for the help

**Comment by Mohron** [comment]
`/sponge:callback 1bdd405f-b1d6-4095-affc-cb78d17759bd` just means you clicked on text that has an action attached to it.  Please send the full log and the schematic too.

**Comment by Mohron** [comment]
You edited your comment so I guess that means you solved your problem. Closing.
