### ISSUE TITLE
Island creation fails silently to place block, reboot required to recover

### ISSUE THREAD

**Issue by LemADEC** [DevOnTheRocks/SkyClaims#101]
### Version:
- **Sponge:** spongeforge-1.12.2-2768-7.1.2-RC3493
- **SkyClaims:** SkyClaims-0.27.2-S7.0-BETA
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.662
- **Permissions:** LuckPerms-Sponge-4.2.67build727

### Expected Behavior:

Island creation/reset actually placing blocks.

### Actual Behavior:

Island creation only delete the claim whether during first creation or reseting.
There's no logs nor chat messages
A reset is required to recover.
https://gist.github.com/LemADEC/a044710b854d6273628ab822059a9abb

### Steps To Reproduce:

unknown at this time

**Comment by Mohron** [comment]
As I stated in discord, SkyClaims has no control over the placement or removal of blocks. It goes down the sponge rabbit hole and ends up here:
https://github.com/SpongePowered/SpongeCommon/blob/b0feef01ce9dd52e0782cf70b8550b324c6aca65/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L655-L820

Trying to change a block returns a boolean, sure, but that's *67,108,864* setBlocks and logging that would be absolutely horrible.

Not to mention, this is only a recent problem which points to the piece of the puzzle that is constantly updating, Sponge. To that end, I have no intention of investigating this further as the issue with blocks being set or not set are outside my codebase and I don't have the time to research and report issues to sponge myself.
