### ISSUE TITLE
The root must be a PluginContainer Error

### ISSUE THREAD

**Issue by JoeSGT** [DevOnTheRocks/SkyClaims#102]
### Version:

- **Sponge:** 1.12.2-2768-7.1.2 
- **SkyClaims:** 0.27.2-S7.0-BETA
- **GriefPrevention:** 1.12.2-4.3.0.662
- **Permissions:** LuckPerms-Sponge-4.3.29
- Nucleus 1.6.3-S7.1-MC1.12.2-plugin
### Expected Behavior:
When i type `/is sethome` an error brings up and unable to sethome using skyclaims commands

### Actual Behavior:

https://pastebin.com/raw/rL1QnnMT
### Steps To Reproduce:
Have the version i have and then attempt to sethome using skyclaims

**Comment by Mohron** [comment]
Fixed in Nucleus.
https://github.com/NucleusPowered/Nucleus/releases/tag/1.8
