### ISSUE TITLE
You don t have permissions to travel to (world name)

### ISSUE THREAD

**Issue by ghost** [DevOnTheRocks/SkyClaims#106]
spongeforge-1.12.2-2768-7.1.5
SkyClaims-0.27.2-S7.0-BETA
griefprevention-1.12.2-4.3.0.662
LuckPerms-Sponge-4.3.75
### Expected Behavior:
After creating a permissions for guests (called group.deafult) and writing command /is create i expect that i have created a island and i can teleport there and do skyblock stuff

### Actual Behavior:
island creates and (title name) so you stay at deafult map. you don t tp to the skyblock map.

all logs and a server files are there: https://drive.google.com/file/d/1gbngXz1l58SVMl92nLIFq0U7DZ4s-vUW/view?usp=sharing (120mb)
### Steps To Reproduce:
1.Run server
2.Create new account
3./is create
4./is spawn and you can see no permissions. You can see it even in stage 3
or
1.Log in to test4 account
2.passowrd is test4
3./is spawn
4.same error
tried to use nucleus.world permissions i put some permission to true after all permissions to true then i just know that i am totall idiot that can t set up even permissions

Sorry for every mistake but when i was writing it was that i late i allmost slept on my laptop...............

**Comment by SubtypeZero** [comment]
https://github.com/lucko/LuckPerms/wiki

**Comment by Mohron** [comment]
SkyClaims does not restrict teleportation across worlds in any way.
