### ISSUE TITLE
/is lock not working

### ISSUE THREAD

**Issue by Yorkforce** [DevOnTheRocks/SkyClaims#107]
### Version: SkyClaims-0.27.2-S7.0-BETA

- **Sponge:** spongeforge-1.12.2-2768-7.1.6-RC3671
- **SkyClaims:** SkyClaims-0.27.2-S7.0-BETA
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.662
- **Permissions:** LuckPerms-Sponge-4.4.7

### Expected Behavior:
When using /is lock it should prevent any non members entering the island region

### Actual Behavior:
With /is lock used, anyone can enter.

![Islock1](https://user-images.githubusercontent.com/1526195/56628098-72b64a00-6640-11e9-997f-cccad2635623.png)

![IsLock2](https://user-images.githubusercontent.com/1526195/56628106-777afe00-6640-11e9-925b-5fce590b1784.png)

Only with undefined set to false via manually changing the GP flag does it stop players entering the claim, the 'personal claim' flag doesn't seem to work.

I'm not sure if this is a skyclaims issue or a GP issue.

### Steps To Reproduce:

**Comment by Mohron** [comment]
Has this issue been resolved in the snapshot I provided you on #108?

**Comment by Yorkforce** [comment]
Sort of, when you `/is lock` anyone inside the island gets kicked to spawn and they cant fly/get in, but if you do `/is unlock` they still cant enter the claim, the `/cf` flag remains on enter-claim=false after using `/is unlock`

**Comment by Mohron** [comment]
The cf flag is actually not set by SkyClaims. Just change your default (pink) to true and test it again.

**Comment by Yorkforce** [comment]
We tested it again, unfortunately it doesnt seem to be working, after setting the enter-claim default to true, using `/is lock` again kicks player to the spawn but they are able to fly right back into the island claim

**Comment by Mohron** [comment]
I think I found the problem. Give this build a shot.
[SkyClaims-0.28.0-S7.1-SNAPSHOT-all.jar.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3169695/SkyClaims-0.28.0-S7.1-SNAPSHOT-all.jar.zip)

**Comment by Mohron** [comment]
https://github.com/DevOnTheRocks/SkyClaims/releases/tag/beta-28-pr1

**Comment by Mohron** [comment]
Closing due to no response.
