### ISSUE TITLE
Add keep inventory default setting permission/option

### ISSUE THREAD

**Issue by Yorkforce** [DevOnTheRocks/SkyClaims#108]
### Version: SkyClaims-0.27.2-S7.0-BETA

- **Sponge:** spongeforge-1.12.2-2768-7.1.6-RC3671
- **SkyClaims:** SkyClaims-0.27.2-S7.0-BETA
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.662
- **Permissions:** LuckPerms-Sponge-4.4.7

### Expected Behavior:
Adding the skyclaims.admin.reset.keepinv permission should allow users to keep thier inventory when using the /is reset command.

### Actual Behavior:

Inventory gets cleared regardless.

**Comment by phit** [comment]
thats not what the permission does, it allows you to not reset it when using the reset command by doing `/is reset <schem> true`

**Comment by Yorkforce** [comment]
Not sure what you mean?

If they have that permission node and use `/is reset` and then select a schematic from the list in chat, then it doesnt stop the inventory being cleared?
Or if they used `/is reset <schematic name>` directly, then it works?

**Comment by phit** [comment]
> .. then it doesnt stop the inventory being cleared?

correct

> Or if they used `/is reset <schematic name>` directly, then it works?

no, they need to specifically do `/is reset <schematic name> true`
note the true at the end, its an admin argument

**Comment by Yorkforce** [comment]
Dang, ok thanks.

I don't suppose we could get an optional permission node for players to keep inventory on an `/is reset` command?

**Comment by Mohron** [comment]
Like @phit explained, the permission gives you access to the command argument that lets you decide to keep inventory, it does not change the default behavior of the command.

I'll add a way to change the default behavior in addition to giving access to selecting one or the other with the command.

**Comment by Yorkforce** [comment]
Very much appreciated, thank you!

**Comment by Mohron** [comment]
@Yorkforce give this build a try for this and #107.
 
The changelog can be found [here](https://github.com/DevOnTheRocks/SkyClaims/blob/release/beta-28/CHANGELOG.md).
 
[SkyClaims-0.28.0-S7.1-SNAPSHOT-all.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3110497/SkyClaims-0.28.0-S7.1-SNAPSHOT-all.zip)

**Comment by Yorkforce** [comment]
Does that need compiling into a .jar @Mohron ? Or just renaming into a .jar?
Have to forgive me, I'm not really a coder, just a server admin.

**Comment by Mohron** [comment]
@Yorkforce no its a jar already, github just doesn't let you upload jars to issues. A jar is a zip so I just renamed it for upload

**Comment by Yorkforce** [comment]
Gotya, thanks again I will give it a whirl!

**Comment by Yorkforce** [comment]
Got this when running `/is reset` then clicking on a schematic from the list in chat.

https://pastebin.com/UUrskcRa

![IsError](https://user-images.githubusercontent.com/1526195/56664778-a628c100-66a0-11e9-9b69-cd32e89f06f5.png)

**Comment by Mohron** [comment]
I ended up reworked the keep/clear inventory stuff again. Make sure you take another look at the changelog before updating. The changelog can be found [here](https://github.com/DevOnTheRocks/SkyClaims/blob/release/beta-28/CHANGELOG.md).

[SkyClaims-0.28.0-S7.1-SNAPSHOT-all.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3113945/SkyClaims-0.28.0-S7.1-SNAPSHOT-all.zip)

**Comment by Yorkforce** [comment]
Still getting errors when running `/is reset`

https://pastebin.com/QBtK98dV
and after using `/is delete` then `/is create` i got this, the old island remained
https://pastebin.com/ugi7MFH9

Just to confirm I am not using any of the new keepinv perms or editting the new config options, this is just updating the plugin as is and running the commands.

**Comment by Mohron** [comment]
Blocked by https://github.com/SpongePowered/SpongeCommon/issues/2251

**Comment by Yorkforce** [comment]
I updated to SpongeForge 3682 which includes the NPE fix but I am still getting the nullpointerexception when running /is reset :(

https://pastebin.com/92wCf4gT

I dont know if this is related, probably not but islands are not being deleted properly either, the new island gets created underneath the old one, the schematic area size seems to be choosing the old islands original spawn point to generate down from (aka in the pic below the empty space above the island at the bottom is the size of the area i saved when creating the schematic, around 15 blocks space from the islands actual edges)

This also occurs on version 0.27.2

![isdelete](https://user-images.githubusercontent.com/1526195/56909968-4e73c680-6aa1-11e9-92ce-dadd1721ad60.png)

**Comment by Mohron** [comment]
The sponge common bug I reported was not the only one I identified. It was just one I could not fix within my code. I'm doing some refactoring of the regen code so once I'm done, I'll provide you a updated build.

**Comment by Mohron** [comment]
[SkyClaims-0.28.0-S7.1-SNAPSHOT-all.jar.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3146115/SkyClaims-0.28.0-S7.1-SNAPSHOT-all.jar.zip)

**Comment by Yorkforce** [comment]
Sorry for the delay, wanted to get a proper test server online first.

Thanks Mohron for adding all these new features, they will be really handy for our players!

Edit: May have spoke to soon:
https://pastebin.com/RuQwa69q

But the island schematic mostly generates ok, all the blocks are there but the tinkers smeltery is inactive/disabled (on the old version it stayed active) not sure if thats whats causing the console error.
I also noticed spongeforge did some changes to schematics yesterday in RC3697, we are currently using RC3701, also not sure if thats related.

Edit 2: Definitely spoke to soon:
https://pastebin.com/FRiygAWA

Using `/is create` works fine (except the first error linked) unfortunately using `/is reset` and selecting a listed schematic (doesn't matter which) throw the above error and fails to reset/create the new island.

It also seems some of the old schematic is getting left behind after doing `/is delete` and then `/is create`:
![leftover](https://user-images.githubusercontent.com/1526195/57565209-6278cb80-73b1-11e9-9b41-6cb2182c6352.png)

**Comment by Yorkforce** [comment]
oki yep running into serious issues now, not sure why one schematic works ok but another one doesnt:

![leftover2](https://user-images.githubusercontent.com/1526195/57565282-cfd92c00-73b2-11e9-9b15-5dfb2546038e.png)

You can see the old island above and the new one isn't generating slabs or chiseled blocks for some reason, this is how its supposed to look:

![SF4TheHouse](https://user-images.githubusercontent.com/1526195/57565287-0c0c8c80-73b3-11e9-97c9-ce628990f66a.png)

Full error from log after using `/is delete` and `/is create`
https://pastebin.com/WeswHABq

**Comment by Mohron** [comment]
Something isn't right with that error... That has to belong to an old version because the stack trace is pointing to lines that no longer exist. Are you sure you're running the latest snapshot I provided? Also, if the schematic itself isn't being copied incorrectly, there are bigger problems because that's something I have no control over. It's handled completely by Sponge.

**Comment by Yorkforce** [comment]
You were right, sorry it was 2am when I found out none of the island schematics were working, was 6am by time i got them sorted (5 SF4 servers). I must have reuploaded one of the old downloads, the file sizes were different.
I'm testing with the latest snapshot now, will report back.

**Comment by Yorkforce** [comment]
`/is create` works ok but it has errors

`/is reset` doesn't work, you get teleported to the spawn and the island never gets created, looks like its clearing the old islands now though.

https://pastebin.com/jZSjjpXe

The SpongeForge schematic changes occured in 1.12.2-2825-7.1.6-RC3697
https://github.com/SpongePowered/SpongeForge/commit/0384aa2e494b0add9e827b6e47a4b9179542e87e

**Comment by Mohron** [comment]
This should fix my bug. The all sponge error on the other hand probably has to do with the updated schematic implementation. There were no changes to the API so I don't need to make changes in SkyClaims for it. it's likely there's a SpongeCommon bug if you continue getting stacktraces with just Sponge in it.

[SkyClaims-0.28.0-S7.1-SNAPSHOT-all.jar.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3169288/SkyClaims-0.28.0-S7.1-SNAPSHOT-all.jar.zip)

**Comment by Yorkforce** [comment]
Yep working well now on /is reset

Thanks again Mohron!

I have reported the Archetype error to spongeforge here, hopefully it will be fixed soon:
https://github.com/SpongePowered/SpongeForge/issues/2748

**Comment by Mohron** [comment]
Yeah... I forgot to make sure I called the reset commands on the server thread. It doesn't like it if you do it Async lol.

Anyways, have I met your requirement for this request?

**Comment by Yorkforce** [comment]
Above and beyond, thankyou!
