### ISSUE TITLE
Error expanding island

### ISSUE THREAD

**Issue by HeberonYT** [DevOnTheRocks/SkyClaims#110]
### Version:

- **Sponge:** spongeforge-1.12.2-2825-7.1.6.jar
- **SkyClaims:** SkyClaims-0.28.0-S7.1-PR1-plugin.jar
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.689.jar
- **Permissions:** LuckPerms-Sponge-4.4.26.jar

### Actual Behavior:
The command `/is expand <blocks>`, does not increase in size and throws the following error in the server console:
LOG: https://pastebin.com/raw/FzmuM9jc

### Steps To Reproduce:
Use command `/is expand 2`

**Comment by Mohron** [comment]
Update to https://github.com/DevOnTheRocks/SkyClaims/releases/tag/beta-28-pr2

**Comment by HeberonYT** [comment]
Thanks for the update so fast, now it seems to work, although I have another problem.

I'm not sure to report it here or to LuckPerms, but I'll explain it to you because your plugin is affected.

After downloading your new update, try to expand my own island to verify its operation, but I am receiving the message "You can not expand Heberon's island greater than 128x128"
So I checked the META LP entries to verify that my "op" group had a maximum size set.
But this seems to be an error, since the image shows how my group "op" has the entry "skyclaims.max-size = 240", but for some reason the plugin continues checking first the entry of the lowest group "default"
I already tried to reload plugins and clean LP cache but I still get the same error.
![Screenshot_4](https://user-images.githubusercontent.com/13698597/59150479-15a50680-89ea-11e9-8a00-a36418c608b4.png)

**Comment by Mohron** [comment]
Ya, I had already patched that bug, I just hadn't uploaded a jar to Github yet. I'll reopen this for the new bug though.

**Comment by Mohron** [comment]
I added a logger for the max-size option to this build. If you don't get back the value you expect, you might need to adjust the weight of your groups in LP.
_This is just a jar, no need to unzip, just remove the ".zip"_
[SkyClaims-0.28.0-S7.1-SNAPSHOT-plugin.jar.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3268972/SkyClaims-0.28.0-S7.1-SNAPSHOT-plugin.jar.zip)

**Comment by HeberonYT** [comment]
Thanks, I'll try it tomorrow when I have a little time and I'll tell you the results.

**Comment by HeberonYT** [comment]
It seems that now it works correctly, I actually had to assign a weight to each group, but after that it worked.
Another question, do you currently have support for the generation of Stoneblock-type islands? Or should I modify the code personally?

**Comment by Mohron** [comment]
Works out of the box in the pre-release. I've also provided the schematic with the plugin. 

https://github.com/DevOnTheRocks/SkyClaims/blob/release/beta-28/src/main/resources/stoneblock2.schematic
