### ISSUE TITLE
Unable to create new islands

### ISSUE THREAD

**Issue by Yorkforce** [DevOnTheRocks/SkyClaims#112]
### Version:

- **Sponge: spongeforge-1.12.2-2825-7.1.6 STABLE** 
- **SkyClaims: 0.28.0-S7.1-PR3** 
- **GriefPrevention: 689** 
- **Permissions: Luckperms 4.4.7** 

### Actual Behavior:

On our more populated server we updated the plugin to PR3, I was able to /is reset fine, but once I /is delete and tried /is create I got:

Failed to create claim: CLAIM_EVENT_CANCELLED

The debug logs showed this:
https://pastebin.com/73PKi6nv

**Comment by Mohron** [comment]
I added some additional logging so we can hopefully get more info on what canceled the claim event. Try this build. Just remove the `.zip` I added in order to upload it.
[SkyClaims-0.28.0-S7.1-SNAPSHOT-plugin.jar.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3312551/SkyClaims-0.28.0-S7.1-SNAPSHOT-plugin.jar.zip)

**Comment by Yorkforce** [comment]
It says
![scclaim](https://user-images.githubusercontent.com/1526195/59895585-fe4c1d00-93dc-11e9-8570-57447523f9cd.png)

It has also spread to our other 3 SF4 servers now too, I was initially able to create an island ok, but now I get that message on all servers.

On our new SF4 server (that we opened tonight) there were 2 islands that were created ok in that world/dimension before the issue above occurred, we didn't change anything from when it created islands ok to the issue popping up:
![scclaim2](https://user-images.githubusercontent.com/1526195/59895789-c98c9580-93dd-11e9-8906-e4e4be173911.png)

**Comment by Mohron** [comment]
Try this.
[SkyClaims-0.28.0-S7.1-SNAPSHOT-plugin.jar.zip](https://github.com/DevOnTheRocks/SkyClaims/files/3314103/SkyClaims-0.28.0-S7.1-SNAPSHOT-plugin.jar.zip)

**Comment by Mohron** [comment]
Did you get a chance to test the latest build? Are you still having issues?

**Comment by Mohron** [comment]
Closing due to no response.
