### ISSUE TITLE
Server Timeout on is reset

### ISSUE THREAD

**Issue by HeberonYT** [DevOnTheRocks/SkyClaims#113]
### Version:

- **Sponge:** spongeforge-1.12.2-2825-7.1.6.jar
- **SkyClaims:** SkyClaims-0.28.0-S7.1-PR3-plugin.jar
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.689.jar
- **Permissions:** LuckPerms-Sponge-4.4.26.jar

### Actual Behavior:

Hi.
I'm using this plugin in Stoneblock 2
But there is a problem when the user restores their island, because the regeneration is too time consuming and causes the server to close because it does not respond.
Attached the crash and the last log.

### Steps To Reproduce:

use command /is reset

Crash: https://pastebin.com/raw/Bf9RVJ19
Log: https://pastebin.com/raw/ASu77nzi

**Comment by Mohron** [comment]
Watchdog crashes are not a bug. The entire generation process is done as async as possible.

You need to fix your configuration. You're having skyclaims void the world...
`[13:44:08] [pool-3-thread-13/INFO] [skyclaims]: Using preset code '' to regenerate region.`

**Comment by HeberonYT** [comment]
Excuse the question, but how can I solve that?
Any special adjustment?

**Comment by Mohron** [comment]
skyclaims.conf > World > `Preset-Code="minecraft:bedrock,254*minecraft:stone,minecraft:bedrock"`

This will change the default /is reset and delete to create the stoneblock world instead of voiding the entire region which is not performant when it's solid stone to start with.

**Comment by HeberonYT** [comment]
Thanks for that information, I did not know.
regards
