### ISSUE TITLE
/isa Command not found

### ISSUE THREAD

**Issue by nurdism** [DevOnTheRocks/SkyClaims#115]
### Version:
- **Sponge:** spongeforge 1.12.2-2838 7.1.7 RC3902
- **SkyClaims:** SkyClaims 0.28.0-S7.1 PR3
- **GriefPrevention:** griefprevention 1.12.2 4.3.0.692
- **Permissions:** LuckPerms 4.4.28

### Expected Behavior:
`/isa` to be a command

### Actual Behavior:
`/isa` is not found as a command

### Steps To Reproduce:
load up server type `/isa`

**Comment by nurdism** [comment]
rip, just read the release notes saw 

Removed `/isa` & `/is admin`

**Comment by Mohron** [comment]
https://github.com/DevOnTheRocks/SkyClaims/releases/tag/beta-28-pr3
