### ISSUE TITLE
error

### ISSUE THREAD

**Issue by baustien** [DevOnTheRocks/SkyClaims#117]
![111111](https://user-images.githubusercontent.com/56314013/66414526-dc14f400-e9f9-11e9-8ff5-10275bd02730.PNG)

- **Sponge:** spongeforge-1.12.2-2825-7.1.6.jar
- **SkyClaims:** SkyClaims-0.27.2-S7.0-BETA.jar
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.692.jar
- **Permissions:** LuckPerms-Sponge-4.3.75.jar

### Expected Behavior:

command not work 

### Actual Behavior:

https://pastebin.com/2XajRU4h

**Comment by ktole1999** [comment]
if you are using 692 on GP then update sponge to latest.

**Comment by Mohron** [comment]
Update sponge, this is not a SkyClaims issue.
