### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by bigenergy** [DevOnTheRocks/SkyClaims#118]
Are you planning to finally implement Mysql support?

**Comment by Mohron** [comment]
It's not a priority as it is unnecessary. Islands persist minimal data beyond what they can derive from the GP claim that they wrap. GP uses all flat files and SkyClaims relies on it so the value of having the data in a MySQL database is minuscule, if any. Also the island data is cached so once loaded, there is very little IO overhead.

**Comment by bigenergy** [comment]
My friend kept a server with your plugin, and when he got in over 50 people, your plugin database broke

**Comment by dvhaldane** [comment]
I’ve ran this plugin on servers with hundreds of historical users with no issue. It’s been a some iterations ago, but I recall this plugin referencing users by UUID.  A hard cap of 50 players doesn’t make much sense.

**Comment by Mohron** [comment]
> My friend kept a server with your plugin, and when he got in over 50 people, your plugin database broke

I have a db copy from a server with `7,593` islands. They did not have DB issues. Again, as long as GD does not have DB support, adding it to SkyClaims is pointless.
