### ISSUE TITLE
Failed to locate default world 'world'

### ISSUE THREAD

**Issue by HeberonYT** [DevOnTheRocks/SkyClaims#119]
### Version:

- **Sponge:** spongeforge-1.12.2-2838-7.1.7.jar (recomended)
- **SkyClaims:** SkyClaims-0.28.0-S7.1-BETA-plugin.jar
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.692.jar
- **Permissions:** LuckPerms-Sponge-4.4.31.jar

### Actual Behavior:
When starting the server the console throws too much spam and no Skyclaims command works, all the commands entered throw the error:
https://i.imgur.com/OuaKhjG.png

LOG: https://pastebin.com/raw/GQivdnVY

**Comment by Mohron** [comment]
Do you have mystcraft installed? Another server had this issue before and they believed that mystcraft was responsible for renaming the world without their knowledge. The level.dat will have to be fixed if this happened to you.
