### ISSUE TITLE
Island not creating claim in correct dimension

### ISSUE THREAD

**Issue by DrZoddiak** [DevOnTheRocks/SkyClaims#12]
I'm having the issue with islands not auto-claiming when I have the islands spawn in a different dimension that's not world. 
I have a dimension called SkyIslands, I changed it in the config and the islands spawn in that dimensions, but they don't get claimed.
The Claim does however load in the default world instead of the dimension I had selected.

**Comment by Mohron** [comment]
@DrZoddiak This should be fixed in c906e4d71aceda803a362983b7f3ac9d9a84f70c. Let me know if you still have issues!
