### ISSUE TITLE
turn off paying for expansion

### ISSUE THREAD

**Issue by MagicCheese1** [DevOnTheRocks/SkyClaims#121]
### Version:
- Sponge v.1.12.2-2838-7.1.7
- skylclaims v2.20
- griefprevention v1.12.2-4.3.0.692
- luckperms v4.3.75

When a player wants to use /is expand to expand their island they need to pay and I can't seem to find an option to turn that off

**Comment by Mohron** [comment]
If you want your players to expand for free, just give them a min island size the same as the max you want them to have. There's no point in making them run a command to max their island if there's no cost to doing so.

So unless you can explain how it makes sense to make your player's run the command if there's no limit to them using it, I'm not likely to add a free option.

**Comment by MagicCheese1** [comment]
players get higher ranks when they play for longer and the higher ranks have higher max sizes so when a new player with the rank new creates a 30x30 island which is his max and then ranksup he can expand the island

**Comment by Mohron** [comment]
Just increase their min size and it will automatically expand when the server restarts or the island owner logs on.

**Comment by MagicCheese1** [comment]
oh ok
