### ISSUE TITLE
After using '/ is kick <user>', <user> 's backpack is emptied.

### ISSUE THREAD

**Issue by anytinz** [DevOnTheRocks/SkyClaims#124]
### Version:

- **Sponge:** spongeforge-1.12.2-2838-7.1.9
- **SkyClaims:** 0.29.1-S7.1-BETA
- **GriefPrevention:** 1.12.2-4.3.0.692
- **Permissions:** LuckPerms-Sponge-5.0.88

### Expected Behavior:

After using '/is kick <user>' a player to kick island members.

### Actual Behavior:

'/ is kick <user>' worked, but he also emptied <user> 's backpack.

### Steps To Reproduce:

Whether the player is offline or not, simply using ‘/ is kick <user>’ will clear his backpack.

**Comment by Mohron** [comment]
Next time try reading the docs. This is a feature you can configure by using permissions.

https://github.com/DevOnTheRocks/SkyClaims/blob/sponge/api-7/src/main/java/net/mohron/skyclaims/permissions/Permissions.java
