### ISSUE TITLE
Distance between islands 

### ISSUE THREAD

**Issue by PopcornG3** [DevOnTheRocks/SkyClaims#127]
Hello ! 

Version:

Sponge: spongeforge-1.12.2-2838-7.2.1

SkyClaims: SkyClaims-0.29.1-S7.1-BETA

Grief prevention : griefprevention-1.12.2-4.3.0.692

Permissions: LuckPerms-Sponge-5.1.0

———————————————————

I would like to ask you how should I configure to change the distance between the islands which is only 500 blocks at the moment 

Thank you

**Comment by Mohron** [comment]
As detailed on the wiki, SkyClaims islands are region-based (the individual files MC saves the world to) and therefore the distance between islands is not configurable separate of the size of islands. The larger your islands, the less space in between.

https://devontherocks.github.io/SkyClaims/#/island-layout

**Also, GP and SkyClaims for GP are no longer supported.**

**Comment by PopcornG3** [comment]
Ok thank's for your fast answer ! but i don't unerstand " Also, GP and SkyClaims for GP are no longer supported." i can delete GP on my server ?

**Comment by Mohron** [comment]
As you can see [here](https://github.com/MinecraftPortCentral/GriefPrevention):
> GriefDefender has replaced GP. See github link for latest information. https://github.com/bloodmc/GriefDefender

SkyClaims development has continued, but only for GriefDefender. Releases are available here on GitHub:
https://github.com/DevOnTheRocks/SkyClaims/releases

**Comment by PopcornG3** [comment]
But now i can't use /gd trust my server response : Could not trust "playername". A plugin has denid it !

https://i.imgur.com/zfAdQqA.png
![fky6WOX](https://user-images.githubusercontent.com/5053608/81982214-bf950600-9631-11ea-9e1e-50ec8e8121ab.png)
![iKszxcA](https://user-images.githubusercontent.com/5053608/81982216-c02d9c80-9631-11ea-80e4-a6e30dd6dea5.png)
