### ISSUE TITLE
No monster damage

### ISSUE THREAD

**Issue by Slodrein** [DevOnTheRocks/SkyClaims#128]
Sponge: spongeforge-1.12.2-2838-7.2.1

SkyClaims: SkyClaims-0.30.0-S7.1-GRIEF-DEFENDER-plugin

Grief prevention : griefdefender-sponge-1.2.4-B15

Permissions: LuckPerms-Sponge-5.1.0

Hello, 

None of my players take damage from monsters
How can i change this option ?
thanks !

**Comment by Mohron** [comment]
SkyClaims does not have any interaction with mob damage. You likely have something misconfigured/wrong permissions in GriefDefender.
