### ISSUE TITLE
Empty Nether 

### ISSUE THREAD

**Issue by Slodrein** [DevOnTheRocks/SkyClaims#129]
Sponge: spongeforge-1.12.2-2838-7.2.1

SkyClaims: SkyClaims-0.30.0-S7.1-GRIEF-DEFENDER-plugin

Grief prevention : griefdefender-sponge-1.2.4-B15

Permissions: LuckPerms-Sponge-5.1.0

Hello,

The world of nether does not generate we are only on an obsidian platform

**Comment by Mohron** [comment]
Check your nether's Sponge world conf for a `world-generation-modifier`:

```hocon
sponge {
    world {
        # If 'true', this world will load on startup.
        load-on-startup=true
    }
    # World Generation Modifiers to apply to the world
    world-generation-modifiers=[
        "skyclaims:void"
    ]
}
```

Remove it and delete your nether world folder to regen it. If you don't have a modifier, skyclaims is not contributing your void gen.

![image](https://user-images.githubusercontent.com/3623122/82500279-1599fb80-9ac1-11ea-9524-c126d3baa312.png)

**Comment by Slodrein** [comment]
Ok thank's
