### ISSUE TITLE
/is delete

### ISSUE THREAD

**Issue by Slodrein** [DevOnTheRocks/SkyClaims#130]
Sponge: spongeforge-1.12.2-2838-7.2.1

SkyClaims: SkyClaims-0.30.0-S7.1-GRIEF-DEFENDER-plugin

Grief prevention : griefdefender-sponge-1.2.4-B15

Permissions: LuckPerms-Sponge-5.1.0

Hi.

When one player use /is delete.
All connected player inventory are deleted !

**Comment by Mohron** [comment]
If you haven't configured keep inventory perms, anyone who's part of an island will have their inventory wiped when it is deleted.

https://github.com/DevOnTheRocks/SkyClaims/blob/sponge/api-7/src/main/java/net/mohron/skyclaims/permissions/Permissions.java#L47-L56
