### ISSUE TITLE
cant disable End and Nether void

### ISSUE THREAD

**Issue by Irgendwer01** [DevOnTheRocks/SkyClaims#134]
### Version:
- **Sponge: 2838-7.2.4-RC4058
- **SkyClaims: 0.29.1-S7.1-BETA
- **GriefPrevention: 4.3.0.692
- **Permissions: Luckperms 5.0.63

### Expected Behavior:
End and Nether isnt void

### Actual Behavior:
End and Nether is void

### Steps To Reproduce:
1. remove DIM1 and DIM-1 from the void list in the config
2. go into the nether and end and see it is still void

**Comment by Mohron** [comment]
Unfortunately, the way sponge modifiers work, it's your sponge config that matters. Check the sponge world config and remove the Skyclaims world modifier. The SkyClaims config just auto installs the modifier when the word is created and does nothing more after a world is created.

# Sponge Config
config/sponge/worlds/%mod%/%dimension%/world/world.conf > `world-generation-modifiers`
