### ISSUE TITLE
Crash on start server (java.lang.NoSuchMethodError: org.bstats.sponge.Metrics2)

### ISSUE THREAD

**Issue by yaroslav4167** [DevOnTheRocks/SkyClaims#135]
### Version:

- **Sponge:**  SpongeForge 1.12.2-2838-7.3.1-RC4094
- **SkyClaims:**  0.30.0-S7.1-GRIEF-DEFENDER
- **GriefPrevention:**  No
- **GriefDefender:** 1.5.3-DEV
- **Permissions:**  LuckPerms 5.2.23

### Expected Behavior:

Successful started server

### Actual Behavior:

[Crash](https://gist.github.com/yaroslav4167/0a03edbf7a2770b5196e4ef4903abf3f)

### Steps To Reproduce:

Put in the plugin folder: SkyClaims, GriefDefender, LuckPerms and let's say Plan (latest version 791) and start server. 
As a result, the server will not start.

This bug did not occur with SkyClaims-0.29.1 and GriefPrevation.
I disabled Metrics in bStats, but the error persisted.

**Comment by Mohron** [comment]
Not a SkyClaims issue exactly... Skyclaims uses a newer version of bStats and something else you have uses an older/incompatible version.

https://github.com/Bastian/bStats-Metrics/issues/63

**Comment by yaroslav4167** [comment]
Ok. Thank you.

**Comment by Mohron** [comment]
There's a build w/o bstats pinned to Discord as a workaround: https://cdn.discordapp.com/attachments/265190931072942080/745428594121244782/SkyClaims-0.30.1-S7.1-GRIEF-DEFENDER-SNAPSHOT-plugin.jar

**Comment by yaroslav4167** [comment]
> 
> 
> There's a build w/o bstats pinned to Discord as a workaround: https://cdn.discordapp.com/attachments/265190931072942080/745428594121244782/SkyClaims-0.30.1-S7.1-GRIEF-DEFENDER-SNAPSHOT-plugin.jar

WOW, it's worked! Thank you very match!
