### ISSUE TITLE
is create gives null error.

### ISSUE THREAD

**Issue by B1ueN0va** [DevOnTheRocks/SkyClaims#136]
### Version:
- **Sponge:** 1.12.2-2838-7.3.0 Forge
- **SkyClaims:** 0.29.1-S7.1-BETA
- **GriefPrevention:** 1.12.2-4.3.0.692
- **Permissions:** Luck Perms 4.2.17

### Expected Behavior:

I expect Skyclaims to create an island

### Actual Behavior:

It doesn't.

### Steps To Reproduce:

Create a Linux Hosted Skyfactory 4 Server, add the above mentioned plugins, and run it.

Error: https://hatebin.com/qfwdjjlhmm

Config: https://hatebin.com/ubecfdmoso

Full Log: https://hatebin.com/vtqqstztkk

**Comment by Mohron** [comment]
GriefPrevention and SkyClaims for GriefPrevention are no longer supported. Migrate to GriefDefender and the latest build of SkyClaims available here on [GitHub](https://github.com/DevOnTheRocks/SkyClaims/releases) or in [Discord](https://discord.gg/EkVQycV).

**Comment by B1ueN0va** [comment]
But that costs $15

**Comment by Mohron** [comment]
It's open-source and free to use... You can build it yourself, you only have to pay if you want support or official builds. Either way I won't support old builds or abandoned software.
https://github.com/bloodmc/GriefDefender
