### ISSUE TITLE
How do I create a Void World for SkyClaims

### ISSUE THREAD

**Issue by subtank** [DevOnTheRocks/SkyClaims#19]
confused about this question a lot of time, can you give me some guide?

**Comment by Mohron** [comment]
SkyClaims does not create a void world for you if that's what you're referring to. Without any other mods or plugins the following setting in you `server.properties` will make the overworld void.
```
level-type=FLAT
generator-settings=3;minecraft:air;127;
```

**Comment by subtank** [comment]
i just used projectworlds plugin to manage my multi world.

**Comment by subtank** [comment]
how the skyclaims use a new world i create for it?

**Comment by Mohron** [comment]
You will have to look into that plugins documentation on setting up world generation settings (the same ones provided could be use for a custom world). I can't provide support for other plugins.

You can set the world to be used by skyclaims in the config.

**Comment by subtank** [comment]
how the skyclaims config read the world? just like. /skyisland or./world/skyislan. to use the skyisland world

**Comment by Mohron** [comment]
By the world's name

**Comment by subtank** [comment]
![image](https://cloud.githubusercontent.com/assets/19743209/22130702/e9dc82de-dee8-11e6-92da-e66e7549f0ce.png)
subtank is a normal world,and skyisland is a viod world i just create for skyland,but it not work...

**Comment by Mohron** [comment]
You need the name from in game. the folder doesn't meant that's it's internal name. I'd recommend using the overworld as you skyclaim dim tbh. But I can look into improving this more later.

**Comment by subtank** [comment]
can you give me a recommend multi world manager?

**Comment by Mohron** [comment]
I just use Nucleus. But then again I believe most of skyclaims users, myself included, are not using an external world for islands.

**Comment by ghost** [comment]
Creating VOID World is very simple, no need edit server.properties:

https://forums.spongepowered.org/t/spongyisland-a-skyblock-plugin-for-sponge/15626/3?u=hunterzcz

**Comment by subtank** [comment]
actually,i just forget close this question.find the way to create the void world.

**Comment by ghost** [comment]
Will be fine add this Q/A to FAQ.

**Comment by Mohron** [comment]
It wouldn't be a bad idea to have a FAQ in the wiki. Anyone is welcome to start the page.

**Comment by subtank** [comment]
I think if you make it noobs,it will be fine. because i put too much time when i first getting start

**Comment by Mohron** [comment]
https://github.com/DevOnTheRocks/SkyClaims/wiki/FAQ
