### ISSUE TITLE
Team Management/Module

### ISSUE THREAD

**Issue by Mohron** [DevOnTheRocks/SkyClaims#20]
Features required for management of teams:
- [x] Add Invite commands/Redirect GP commands to internal system
- [ ] Add MCClans integration for clan "teams"
- [ ] ~~**Team Database Table:**~~
    - [ ] ~~Name~~
    - [ ] ~~Islands~~
    - [ ] ~~Owner/leader(s)~~
    - [ ] ~~Member(s)~~
    - [ ] ~~Playtime (Sum)~~
- [ ] **Permission options:**
    - [ ] Max players per team
    - [ ] Max island(s) per team (possibly also per player on team)
    - [ ] Max playtime for a team before new invites aren't allowed

Decided:
- All Islands will be owned by a team
- All players will be in a team even if it's just them (though this difference will be transparent)

Undecided:
- Will teams have single/multiple leader(s)?
- Team leader transfer vs individual island transfer

**Comment by phit** [comment]
my opinions on the bullet points:

* island should be owned by one player
* there can be managers same thing as gp managers
* players can have one island for themselves but can't be in multiple teams
  * if member (not owner) of a team others in the team can't access players private island
  * member can not make a team for his own island as long hes member of another team
* teams can be transferred to players that dont have an own island

**Comment by curscascis** [comment]
Island should be owned by teams, and teams should be owned by a player, this would be the easiest implementation for all the features including a proper relational DB, and will also make "migration easier". Every island/group of islands has one team. 

There is one leader which can give a mod/admin rank to players they want to for the team.

Ultimately this sort of decision we are hashing out should be configurable by each server considering it really depends on the server needs. I like the idea of assigning multiple islands to a group one island per team member things shareable across them . 

As I stated in my previous document, it would be nice to eventually support "clean player data " for each "island" or separate team allowing players to come and go as they choose in different placesz but  we know the current limitations for that. 

I think previously we talked about having multiple teams that you can be a part of or multiple islands , and it's an idea, but again it's more a server based thing. I still think it would be best to support being a part of 1 team, and later add support for multiple teams per person.
The person who owns the island should be able to transfer it and the person who they transferring it to should have to accept it. If a server administrator does it they should have a confirm as well and the player getting it should still have to accept the claim.

**Comment by elementalistic** [comment]
My 2c.

Make everyone by default join there own team.  This way islands only belong to teams, there is no need for separate code to handle a player island or a team island.

Let Team Leader be Player X
Let Player be Player Y

**The process for joining a team if you already have an island**
- Player X sends an invite to join to Player Y
- Player Y accepts
- Message displayed to Player Y that island will be deleted and inventory wiped _**[What if the new team has an open island slot? perhaps merge the existing island into the team... Mohron]**_
- Player Y confirms
- Deletes existing island/claim for Player Y
- Clear's Player Y's inventory
- Removes the team they are part of (their own island)
- Add them to the new team
- Move them to a location at the new island (if needs be spawning them on a piece of dirt, so if the island is only 1 block, you don't have them spawn and push each other off the block).
- No need to restore inventory, as the team leader would have the 'first join' items. _**[not sure how I feel about this... Mohron]**_

**Team Leader 'leaving the team'**
Assuming 1 leader per team
- If the leader quits, next leader becomes either the one with the longest playtime, or first to join the team out of the remaining players.
- Leader gets his own island auto created if the config for auto create is true
- This would also apply if an admin kicked the player from his team, for example hasn't been on for months and the other members agree

**~Config~ [Permissions... Mohron] Options**
- Max number of players per team
- Max number of islands per team  (so even if it was only 1 player per team, they could have multiple islands)
- Commands to be run on team join and team leave, same as island create and reset

**Admin commands**
- Disband team
- Transfer leadership to another team member
- Kick person from a team

I should still have about 1.8c left. I'll add more as I think of it.

**Comment by Mohron** [comment]
@elementalistic if that's only 0.2c out of 2c, then you must have quite a lot to share. I made an edit and comment on what you have so far.

**Comment by Mohron** [comment]
Superseded by #59. A few items from this plan will be implemented into the invite system at a later date.
