### ISSUE TITLE
Automated Island Cleanup

### ISSUE THREAD

**Issue by Mohron** [DevOnTheRocks/SkyClaims#22]
Add optional automated cleanup of inactive islands.
- [ ] Add a last active date to island data  
- [ ] Use GP last active date to initialize island last active
- [x] Create task to check island for inactivity past threshold set via option
- [x] Add config to set the interval of the inactivity check (15 min default? ~0 to disable~)
- [x] Add a way to list islands by closest to expiration ie. `/is list inactive`
- [x] Add last active data to `/is info`
- [x] Add `skyclaims.expiration` option with default 0 (off)

**Comment by marvin-bitterlich** [comment]
What is the status of this issue? I would love to help speed this up by helping in code, posting a bounty or other things.

**Comment by Mohron** [comment]
Soon:tm:
