### ISSUE TITLE
Generating a Void Nether & End

### ISSUE THREAD

**Issue by Westus** [DevOnTheRocks/SkyClaims#23]
I used these settings to generate the world:
```
level-type=FLAT
generator-settings=3;minecraft:air;127;
```

**Comment by Mohron** [comment]
Use a mod (Yunomakegoodmap) or a world management plugin like PJW or Nucleus' world module. There's also the world gen modifier `sponge:void` that can be used in sponge configs but people have had mixed success using it. Either way, SkyClaims only manages islands at this time, not world generation, sorry.

**Comment by Westus** [comment]
Yunomakegoodmap does not work with the sponge. I used the Nucleus.
```
/world create -g FLAT -d Nether -m sponge:void nether
/world create -g FLAT -d The_End -m sponge:void end
```
/config/sponge/global.conf
```
        portal-agents {
            "minecraft:default_nether"=nether
            "minecraft:default_the_end"=end
        }
```

**Comment by curscascis** [comment]
This issue with sponge was already fixed. And you can also use the botania sky map generator.

**Comment by Mohron** [comment]
@Westus like @curscascis said, the incompatibility withe Sponge has been fixed. If you're still having problems using yunomakegoodmap, you need to update SpongeForge. Either way I'm glad you found something that works for you!
