### ISSUE TITLE
Island reset command for users

### ISSUE THREAD

**Issue by elementalistic** [DevOnTheRocks/SkyClaims#24]
Delete's the users island and creates a new one (in the same region?) using the previous island's schematic.

Some modpack's let you screw up in ways you can't recover from.  For instance FTB infinity skyblock, you start with a water and lava, if you destroy either of these before you can make a bucket and make more water/lava you have to reset.  As there is no way to progress past this point.

**Comment by KiriCattus** [comment]
There already is a feature for this it's just not documented on the wiki

https://github.com/DevOnTheRocks/SkyClaims/blob/development/src/main/java/net/mohron/skyclaims/command/user/CommandReset.java

Either myself or someone else will add it later on today

**Comment by elementalistic** [comment]
Missed that.  Oh well at least I know it's implemented.  Now just to wait on the beta to be put up on Ore.

**Comment by KiriCattus** [comment]
Beta 17 is on ore at the moment that's the latest there is. `/is reset` was added long before beta 17 (Before Febuary 2nd) Either way I've updated the wiki now so have fun :)

[Wiki-Commands](https://github.com/DevOnTheRocks/SkyClaims/wiki/Commands)

**Comment by elementalistic** [comment]
No point keeping this open then.

Thanks.

**Comment by Mohron** [comment]
Honestly don't know we missed it. At least it was already in the in-game help documentation. Thanks for the help @ProxyNeko.
