### ISSUE TITLE
Feature request: challenges

### ISSUE THREAD

**Issue by ghost** [DevOnTheRocks/SkyClaims#25]
Some kind of challenges (like uSkyBlock) will be cool.

**Comment by KiriCattus** [comment]
We would need more detail if we where to even considder this in the future not just point to another plugin as we don't really have the time to be looking into other plugins but from your message it just sounds like your asking for the likes of the Hardcore Questing Mod (HQM) to be added in as a feature is this correct?

That being said this would be a really low priority feature if it was accepted as SkyClaims is still quite young sorry.
Provide more detail on what it is that you want and it may be considdered and possibly added at a later date :)

**Comment by adpking** [comment]
I don't really think this is relevant to the plugin. If anything this deserves the likes of a plugin in itself. SkyClaims is about the management of islands and not the events on them.

**Comment by ghost** [comment]
I think something similar like this: https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/challenges.yml

**Comment by curscascis** [comment]
I agree with coss. This sort of feature is completely irrelevant. The plugin adds a mechanism, and that mechanism is it's focus, isolation of playing areas and their protection. Features like this are not very useful, productive, or practical to have in a plugin that focuses on one mechanism. If you want things like that, you could always add some MMO plugin. There's a lot of options out there when it comes to skyblock maps / modpacks to play, in any case you could always install HQM, or some other similar quest oriented mod and make your own challenges that way.

**Comment by ghost** [comment]
ok

**Comment by Mohron** [comment]
Just for future reference, SkyClaims is not a port of any other SkyBlock plugin and I intend to keep it that way. If you want to request features, make a detailed request of exactly what your looking for, don't just link/name another plugin you want me to knock off.

**Comment by ghost** [comment]
It was link to exact file with example of challenges. Nevermind.
