### ISSUE TITLE
/is list allows users to teleport to others islands

### ISSUE THREAD

**Issue by DrZoddiak** [DevOnTheRocks/SkyClaims#26]
While I understand that users don't really need the command, or have any reason to have it, I figured I'd address it just in case it wasn't the intended design.

Minecraft: 1.10.2
SF: 2147
SC: B-17

When a user uses /is list and click on the purple coordinates they are teleported to another players island without having trust access.

**Comment by KiriCattus** [comment]
This is a bug this should not happen.

**Comment by KiriCattus** [comment]
Will test this and try to duplicate when I get home.
Can you give me the GriefPrevention version please.

**Comment by Mohron** [comment]
@DrZoddiak took someone long enough! So players can /is lock there islands to prevent people from visiting their island. Now what I'd like to know is what you think about it? Obviously GriefPrevention should be protecting players islands and I figured this would be a nice way to be able to show off your island. Tbh, the command should be handled the same way if I keep this design of island lock.

**Comment by KiriCattus** [comment]
Ah my bad I read your message wrong apologies

**Comment by Mohron** [comment]
@ProxyNeko I'm pretty sure you read it right. Yes you can teleport to an unlocked island using the purple coords on /is list.

**Comment by KiriCattus** [comment]
I'll play about with it anyway I interpreted it as players could still do this even while the island was locked

**Comment by adpking** [comment]
Ideally this should be locked by default to prevent confusion with new users

**Comment by KiriCattus** [comment]
Good point. Especially if the player does not know that they can lock the island and suddentl others show up without them wanting it

**Comment by Mohron** [comment]
@cossacksman I agree but then it would have gone completely unnoticed even longer!

**Comment by DrZoddiak** [comment]
I think it'd actually make a nice feature. I had actually assumed the lock/unlock wasn't fully implemented. I was trying to get people to try and teleport to my island using /is spawn without being trusted.
Though, auto-locking would be a good future implementation. Users tend to freak out when strangers are on their island. :+1:

**Comment by Mohron** [comment]
I'll go ahead an switch the default to lock since there's no question that's the right move. What's everyone's thoughts on `/is spawn [name]`, should an unlocked island give you permission to use it as well? Should you only be able to visit an unlocked island while an island member or owner is online?

**Comment by DrZoddiak** [comment]
I think that use of `/is spawn` would be more user friendly for allowing users to teleport. As a comparison, we've seen how long it took for us to find this method. 
As far as member/owner being online. As long as the protection system is working properly (and it seems to be) I see no reason the owner/member would have to be online.

**Comment by Mohron** [comment]
I kinda just snuck this in around the time I added the lock/unlock feature. The feature is incomplete since I can not manage GP flags yet but I thought this was one way to give it purpose.

**Comment by KiriCattus** [comment]
I'd say if a member or the owner of the island is online and a player did /is spawn ProxyNeko that it should ask me to accept if I'm online or have another member accept if the owner has given the members the permission to accept

**Comment by Mohron** [comment]
Default lock value was changed via 41ac56ac4901467d44444f55d52b50f631161a5b

**Comment by Mohron** [comment]
`/is lock` & `/is unlock` can now be used to set other players locks as well as all other players lock status. `/is list` shows all islands but only unlocked islands, island you're a member of or if your an admin can be teleported to.

**Comment by Mohron** [comment]
This feature has received a major overhaul. All islands are once again listed on `is list` and only the islands that you own, are trusted on or are unlocked will allow you to click the Region coords to teleport to the island. `is spawn` now uses the same set of criteria.  If you have any issues, please let me know.
