### ISSUE TITLE
How to use command configs

### ISSUE THREAD

**Issue by subtank** [DevOnTheRocks/SkyClaims#28]
i find a setting commend in .conf file like this
`    # Commands to run on island creation and reset.
    Create-Commands=[]`
it seems like can build a island automatic, how to setting this commands?can you give me some example?

**Comment by Mohron** [comment]
Here's a quick example, not sure if these are even valid commands though. `@p` can be used for the player's name.
```json
Create-Commands=[
    "give @p stick 1",
    "broadcast @p is a noob and had to restart!"
]
```

**Comment by subtank** [comment]
got it.

**Comment by subtank** [comment]
i will try it later and give you feed back.

**Comment by Mohron** [comment]
Let me know if you run into issue with these settings. I'm going to close this issue since there's been no response in over a week.

**Comment by subtank** [comment]
```
Misc {
    # Commands to run on island creation and reset.
    Create-Commands=[]
    # Automatically create an island for a player on join.
    Island-on-Join=true
    # Commands to run on island resets only.
    Reset-Commands=[
        "is create 1"
    ]
}
```
like this ?

**Comment by subtank** [comment]
i am sorry.these days too busy

**Comment by subtank** [comment]
not work

**Comment by Mohron** [comment]
You don't put SkyClaims commands in the config. Resets don't remove the players island and they can't have another. Also the console cannot create an island

**Comment by subtank** [comment]
i just want let the new guy auto create an island.

**Comment by Mohron** [comment]
Reset rebuilds the players island. They don't need a new one.

**Comment by subtank** [comment]
my mistake...sorry.
