### ISSUE TITLE
Island claim "initial-size" resize on server startup bad maths

### ISSUE THREAD

**Issue by elementalistic** [DevOnTheRocks/SkyClaims#29]
Somethings going wrong with the startup resize.

Quick background on how we do permissions, using LP.

On first join, the user is a "guest", we then query our forum for rank info and apply it.  By this stage the island has been created with the guest initial-size of 36 as well as a max-size of 36.

Once the perms load in the initial-size gets changed to (for our supporters) 112, as well as max-size also set to 112.

So on next server restart it tries to expand the claim and this is where the numbers go weird.

Looking at the claim data file for this person,
Creating <Names>'s claim in region (-2, 1). Claimed from -804x, 732z - -733x, 803z. 
So I'm assuming something like this.
```
claim-spawn="-762;72;762"
...
greater-boundary-corner="-733;255;803"
lesser-boundary-corner="-804;0;732"
```
Became what it is now
```
greater-boundary-corner="0;911;623"
lesser-boundary-corner="-625;-913;255"
```

Consecutive manually fixing it and startups keep giving me those numbers.

This is currently applying to 4 of our players, but the server's only been officially up for 2 days now, so likely everyone that isn't just a regular member will be affected.

--Versions--
Sky Factory 3: 3.0.6
Forge: forge-1.10.2-12.18.3.2221-universal.jar
Sponge Forge: spongeforge-1.10.2-2221-5.1.0-BETA-2142.jar
Skyclaims: skyclaims-1.0.0-beta17.jar
LuckPerms: LuckPerms-Sponge-2.17.61.jar
Grief Prevention: griefprevention-1.10.2-2.3.1.251.jar

**Comment by Mohron** [comment]
Fixed via 23f8a6ed7241b71a753bdba14687c00cb29048d3
