### ISSUE TITLE
Data Inconsistency with GriefPrevention

### ISSUE THREAD

**Issue by Slind14** [DevOnTheRocks/SkyClaims#3]
Currently the plugin highly depends on claims. This is an issue in many occurrences.

- GP saves at a different time, the server crashes inbetween GP and SC save
- A claim is being replaced (new uuid)
- A claim is being resized
...

I would suggest going away from storing claim relations all together and instead only storing the region coords.
Then on island load the claim can be retrieved via. coordinates and if it does not exist a new one can be created.

**Comment by adpking** [comment]
I think I misunderstood what you said about storing the claim relations at first, I assume you mean not to store the Claim at all. It's nice to keep track of the claim, and though we might have to consider a few things whilst using it, we can easily replace and resize a claim if necessary; although I can't think of a case where a claim will be resized using this plugin. The Claim system will be abstracted at some point to make GriefPrevention optional, but we've decided to leave this until the new GriefPrevention API as we'd only be making too much work for ourselves doing it now.

**Comment by Slind14** [comment]
Yeah, I encountered an issue where a claim had a new uuid, which broke the creation of new islands because it got the radius from the claim and not the region.
Griefprevention has a lot of coord -> claim resolution to do, so getting the claim from the center coordinates should be super fast. Hence why I recommend it.

**Comment by adpking** [comment]
What kind of scenario makes an existing claim develop a new UUID? How would I re-create that.

**Comment by Slind14** [comment]
Honestly I don't know what the cause of this claim uuid change was. The player didn't recreate it, as he didn't even have the ability to fly to the corners of the region.

**Comment by Mohron** [comment]
Either way, we'll be making claim handling much better in future builds including recreating missing claims. Right now it's a big mess especially since players can't have access to many gp perms in the island world without being able to break their claims.

**Comment by Slind14** [comment]
Just encountered another issue, the same, just the other way around.  The island record does not exist, but the claim does. This causes another issue with island creation as the pattern task is based on the amount of islands while the region.isTaken check is based on claims.

**Comment by Mohron** [comment]
@Slind14 unfortunately, we are not going to be able to provide you support as long as you use an outdated & forked build. But what you are describing as far as region#isTaken has been replaced in bleeding. 
https://github.com/Mohron/SkyClaims/blob/bleeding/src/main/java/net/mohron/skyclaims/world/Island.java#L131

**Comment by Slind14** [comment]
Don't worry, just making you aware of the issue.

**Comment by Mohron** [comment]
Everything GriefPrevention will be getting overhauled for the api release. It should be more complementary and not cause so many issues if the claim data is invalid or missing.

**Comment by Slind14** [comment]
The issue is when GP and SkyClaims save their data at different times. When the server does crash the data between the plugins gets out of sync.

**Comment by Mohron** [comment]
Our data is currently saved on all changes and world save. The only way there should be a disparity is if GP perms are allowed that otherwise need to be denied like abandoned claim create claim etc

**Comment by Slind14** [comment]
Yes, but what happens if GP only saves on world save? If the server does crash before the world save, the island is there but the claim is gone.
You can't relay on the data of another plugin to have the same state as yours.

This happened multiple times already. We have islands where the saved claim does not exist and we have claims where there is no island.
