### ISSUE TITLE
Island reset command broken

### ISSUE THREAD

**Issue by elementalistic** [DevOnTheRocks/SkyClaims#30]
### Version
- **SkyClaims:** Jenkins Build #81
- **GriefPrevention:** 1.10.2-2.3.1.251
- **SpongeForge:** 1.10.2-2221-5.1.0-BETA-2168

### Expected Behavior
Player sent to spawn, 
Island is deleted,
~Claim is deleted,~
New Island made, 
~New Claim set,~
Player sent to island spawn.

### Actual Behavior
Display's message along lines of wait while island resets.  Then throws an error in console. See attached.

[exception](https://hastebin.com/emekeyaleq.sql)

From that stage onwards, /is list and /is info Juni_W would show the island info and the claim was there.  But /is spawn would say no island.  And if standing on the actual island, /is info would say no island.  

We ended up deleting the island, and claim, and removing all blocks, then restarted server.  Island was properly created after Juni_W joined again.  May not have had to restart server in hindsight.

You jokingly said it was probably broken at some point.  And nothing we worked on had anything to do with reset, so it's not my fault, it's yours!  Maths strikes again.

### Steps To Reproduce
Try resetting an island.

**Comment by KiriCattus** [comment]
Please use https://gist.github.com to paste crash or error logs. Don't upload files directly because they don't get downloaded, gist or pastebin/hastebin/ghostbin are good to use.

**Comment by Mohron** [comment]
This is a really weird error, PositionOutOfBoundsException only throws when the position provided to set biome is outside the volume. Only thing is the volume I provide is the World... does your config still have the right world set?

**Comment by Mohron** [comment]
Any news on this @elementalistic? Are you still encountering this issue?

**Comment by elementalistic** [comment]
Haven't had anyone reset since, I'll update to dev and and try to reproduce tonight.

**Comment by elementalistic** [comment]
Is working fine for latest dev build.  So I'm closing this.
