### ISSUE TITLE
about server package 

### ISSUE THREAD

**Issue by subtank** [DevOnTheRocks/SkyClaims#31]
can i make a sky survival package published in our country's bbs?

**Comment by Mohron** [comment]
I'm not sure what you really asking? If you are asking if you can rehost the plugin, generally I'd advise against it since I'd like to make sure user have access to the latest versions but you do have permission to do so. Just read the license terms :p

>4. Conveying Verbatim Copies.
>
> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.
> 
> You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.

>

**Comment by subtank** [comment]
thank you. i will keep updata when you updata plugin.
