### ISSUE TITLE
Non-Default Initial Size option not being applied

### ISSUE THREAD

**Issue by Yorkforce** [DevOnTheRocks/SkyClaims#33]
### Version
- **SkyClaims:** 0.19.0
- **GriefPrevention:** 1.10.2-2.3.1.271
- **SpongeForge:** 1.10.2-2254-5.2.0-BETA-2236
- **Luckperms:** 3.0.50

### Expected Behavior
Giving the `meta.skyclaims\.initial-size.250` option to an individual player should create a claim thats 500x500

### Actual Behavior
Regardless of the `meta.skyclaims\.initial-size.<value>`, it still uses the default config value when creating the claim.
The `meta.skyclaims\.max-size.250` seems to work ok and allows the player to use the /is expand command to reach thier max claim size

### Steps To Reproduce
Give player `meta.skyclaims\.initial-size.250` option
Give player `meta.skyclaims\.max-size.250` option
Player uses /is create or /is restart
use /claimsinfo to see actual claim size

**Comment by phit** [comment]
it's `skyclaims.min-size` the wiki is just outdated https://github.com/DevOnTheRocks/SkyClaims/blob/development/src/main/java/net/mohron/skyclaims/permissions/Options.java#L38

**Comment by Yorkforce** [comment]
Thanks for the info!
