### ISSUE TITLE
Unable to use /is home when not trusted on an island

### ISSUE THREAD

**Issue by DrZoddiak** [DevOnTheRocks/SkyClaims#34]
### Version
- **SkyClaims:** [0.19.0-beta]
- **GriefPrevention:** [2.3.1.272]
- **SpongeForge:** [2231]

### Expected Behavior
[When I use /is home anywhere it should bring me to the place that I had set a home at previously using /is sethome]

### Actual Behavior
[When on an island that I don't have permissions for and I try to use /is home 'You must have permission to set home on this island!' appears. ]

### Steps To Reproduce
[Set a home on an island you're trusted on, go to an island you're not trusted on, use /is home]

**Comment by Mohron** [comment]
https://github.com/DevOnTheRocks/SkyClaims/blob/development/src/main/java/net/mohron/skyclaims/command/user/CommandHome.java#L67-L68
Easy fix... just a fail copy paste bug.
