### ISSUE TITLE
Islands not deleting properly on /is reset and /is delete

### ISSUE THREAD

**Issue by Yorkforce** [DevOnTheRocks/SkyClaims#35]
### Version
- **SkyClaims:** 0.19.0
- **GriefPrevention:** 271
- **SpongeForge:** 2241

### Expected Behavior
Using /is reset whilst having a player specific schematic should delete the previous island completely

### Actual Behavior
Using /is reset is not deleting the old island and will either create a new island inside the old one or place it directly above, using /is reset multiple times will eventually clear the old island properly.

I also noticed that manually /is delete will actually leave the island in place, if you place a block on the deleted island it will replace the block underneath (like the old island blocks are ghost blocks)
However, and this is the strange part, if you relog on the client the old island ghost blocks will actually disappear completely when logging back in, but if you create a new island before this it will leave behind the old island as solid and harvestable blocks

We also had reports of players seeing old /is deleted islands when they created thier first island.

This was all experienced on Sky Factory 3.0.8 modpack.

### Steps To Reproduce
use /is create to make an island
use /is reset to create a new island with a different schematic

**Comment by elementalistic** [comment]
Try doing the /is reset and then going to spawn and back to the island.  It refreshes it for the client, same as relogging.  Though that should be working, so it might be something specific to schematics.

**Comment by Yorkforce** [comment]
Just wanted to add, we have come across another issue with the /is reset command
When typing /is reset and the chat message pops up asking you to click [YES] or [NO], clicking yes will throw a too many arguments error, the player has to actually type '/is reset confirm' to proceed.

Edit: sorry I was missing the skyclaims.arguments.schematics.island permission node, the [YES]/[NO] is working properly now.
/is reset <schematic name> doesn't work tho, comes up with the too many arguments error (I did check all the permissions properly this time)

**Comment by Mohron** [comment]
@Yorkforce Does your default schematic have a space in the name?

**Comment by Yorkforce** [comment]
@Mohron default schematic is just the tree with the default island.schematic

all the other custom ones are all lowercase schematic names, eg theworkshop, thefactory etc

**Comment by Mohron** [comment]
I'm unable to replicate this issue. If you are able to replicate this issue with the latest version of SkyClaims reliably, let me know and I will reopen this issue.
