### ISSUE TITLE
/is create - java.lang.NullPointerException

### ISSUE THREAD

**Issue by Hexport** [DevOnTheRocks/SkyClaims#36]
- **SkyClaims:** - [_0.2.0_]
- **GriefPrevention:** - [_2.3.1.295_]
- **SpongeForge:** - [_5.2.0-BETA-2317_]
- **Sky Factory 3** - [_3.0.8_]
- **LuckPerms** - [_Sponge-3.1.45_]

Trying to create a new island on a fresh server running the mods listed above. 

I get the error pasted in the link in the console and in chat I get, "Error occurred while executing command: null" Other commands also are not working.

Install mods, add permissions to use commands, use commands.

[is create](https://pastebin.com/mMqWkPGt)
[is reset](https://pastebin.com/USdyHMN7)
[isa delete](https://pastebin.com/VuDvFe2j)

Thank you for your mod and assistance. I'm very sorry if this is an obvious issue, but I have been trying to figure this out for a few days now. My server provider has no idea, they referenced an issue here with a similar chat error, but the solution was deleting the .conf file, which had no effect.

**Comment by Mohron** [comment]
Please provide a complete server log file

**Comment by Mohron** [comment]
Are you by chance trying to use MySQL before its finished?

**Comment by Hexport** [comment]
Hey there, here is a [paste](https://pastebin.com/LddztCkJ) of some of the log which contains what you're after, I think. If not here is the [file](https://drive.google.com/open?id=0ByafLpnTZlY2QU9MRlNwc3BXX1k)

**Comment by Hexport** [comment]
I have a MySQL database, but I haven't configured anything to use it no.

**Comment by Mohron** [comment]
What panel is your server hosted through? You're server cannot find the SQLite libraries.
```
[18:45:04] [Server thread/INFO] [STDERR/sponge]: [org.sqlite.SQLiteJDBCLoader:loadNativeLibrary:230]: Failed to load native library:sqlite-3.14.2.1-9c43b442-8859-4eb7-a5b3-a7f2ddc5fb99-libsqlitejdbc.so. osinfo: Linux/x86_64
[18:45:04] [Server thread/INFO] [STDERR/sponge]: [org.sqlite.SQLiteJDBCLoader:loadNativeLibrary:231]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.14.2.1-9c43b442-8859-4eb7-a5b3-a7f2ddc5fb99-libsqlitejdbc.so: /tmp/sqlite-3.14.2.1-9c43b442-8859-4eb7-a5b3-a7f2ddc5fb99-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted```

**Comment by Hexport** [comment]
[Nodecraft](https://nodecraft.com)'s panel. (not the beta version advertised on the homepage)

**Comment by Mohron** [comment]
Well you will have to talk to your host about this issue unfortunately. Tell them your server requires the SQLite DB driver to run a plugin.

**Comment by Hexport** [comment]
Thanks for your time and help. Off to badger support :)
