### ISSUE TITLE
You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by rlemish** [DevOnTheRocks/SkyClaims#37]
String table = "CREATE TABLE IF NOT EXISTS islands (" +
					"island			STRING PRIMARY KEY," +
					"owner			STRING," +
					"claim			STRING," +
					"spawnX			INT," +
					"spawnY			INT," +
					"spawnZ			INT," +
					"locked			BOOLEAN" +
					")";

STRING??? WTF???

**Comment by Mohron** [comment]
Not a very constructive or helpful way to point out an issue but I get your point. I didn't write the database code myself so I never really looked into it.  FYI, this causes no issues with SQLite even if the syntax is wrong.

**Comment by rlemish** [comment]
Ok. Change the STRING to char(36). Thank you

**Comment by adpking** [comment]
It doesn't matter whether it's STRING or char(36) for SQLITE, both of those are assigned to the same affinity; TEXT.
