### ISSUE TITLE
/tpa

### ISSUE THREAD

**Issue by LeChuuck** [DevOnTheRocks/SkyClaims#38]
### Version
- **SkyClaims:** [  0.20.0-beta  ]
- **GriefPrevention:** [_1.10.2-2.3.1.295_]
- **SpongeForge:** [1.10.2-2281-5.2.0-BETA-2379]

### Expected Behavior
[Player trying to teleport /tpa when the other player is on his island]

### Actual Behavior
[When the tpa is accepted it teleport the player to spawn]

### Steps To Reproduce
[/tpa works when the other player is not on his island]

Player has been added to /trust and island is unlocked.

**Comment by Mohron** [comment]
SkyClaims doesn't add tpa so you're going to have to provide details on what you're using ie nucleus, and the relevant version information.

**Comment by LeChuuck** [comment]
Nucleus-1.0.0-PR2-1.10.2-S5.1

**Comment by dualspiral** [comment]
Does this only happen when you add SkyClaims then? Did you try without it?
