### ISSUE TITLE
About SkyClaims' Advice

### ISSUE THREAD

**Issue by CrysisDeathgun** [DevOnTheRocks/SkyClaims#40]
Hi, a Chinese Player here~
Can u add change language text?
I can convert this plugin into simplified Chinese version for use

This,

**Comment by phit** [comment]
see #18

**Comment by Mohron** [comment]
If somebody translates the readme to Chinese I'd be happy to upload it. 
As far as the entire plugin, translatable messages will be added when I get the chance to do the major rewrite I plan to do.

**Comment by CrysisDeathgun** [comment]
yeah i will,so do u want to make a translate text 

:D

**Comment by subtank** [comment]
i still follow this plg and if @Mohron need the readme translate i will do it this night.(about two hours later~) :D 
**updata: job done~**

**Comment by subtank** [comment]
@CrysisDeathgun by the way, if you need some help for use this plugin, see [wiki](https://github.com/DevOnTheRocks/SkyClaims/wiki) or [mcbbs](http://www.mcbbs.net/thread-679896-1-1.html)i will check the bbs and here weekly.

**Comment by Mohron** [comment]
I appreciate your work translating SkyClaims @subtank. I hope I can get proper translation support so I can package your translations with the main releases.

**Comment by subtank** [comment]
@Mohron you can just send email to subtank@qq.com for me or send an skype(spell right?) name so that i can chat with you ASAP

**Comment by subtank** [comment]
@Mohron proper translation? you can just send me an ingame text and i will translation.

**Comment by CrysisDeathgun** [comment]
which language  is u translation bro @subtank

**Comment by subtank** [comment]
@CrysisDeathgun simplified Chinese

**Comment by CrysisDeathgun** [comment]
@subtank yah i view ur post on the MCBBS ,说白了我是从mcbbs帖子过来的 最近版本一直在修bug 玩家有点吃不消 而且反编译成功率不是很大 所以自己来github了 XD

**Comment by subtank** [comment]
@CrysisDeathgun 行吧。。。以后尽量不要反编译了。影响不好。。。很多coder包括我，对于反编译都是很反感的。。。

**Comment by CrysisDeathgun** [comment]
@subtank 好的:D

**Comment by Mohron** [comment]
I have no idea what is going on here lol. Do I need to do anything before closing this ticket? I'll get the translated Readme merged soon.

**Comment by subtank** [comment]
@Mohron nothing...this guy @CrysisDeathgun is the hard-translation guy that i was told you before.just close this is ok.

**Comment by CrysisDeathgun** [comment]
@Mohron  nothing thx :D

**Comment by subtank** [comment]
@Mohron in one words,your work has lots of user in chinese,so Chinese player need Chinese.
