### ISSUE TITLE
Loot cleaning.

### ISSUE THREAD

**Issue by DeltaVetal26** [DevOnTheRocks/SkyClaims#43]
Good evening. I already addressed to you with a similar problem. Here is the last ticket - https://github.com/DevOnTheRocks/SkyClaims/issues/39 . In the new version things are also not cleaned, but at the same time, the chests and blocks, which fall out of them visually, do not disappear. The problem in the video is - https://youtu.be/MNYUtD-FsXc . I'm waiting for an early reply. Thank you!

**Comment by Mohron** [comment]
What version are you running? You should not be able to stay on the island during a reset. If you have your world spawn on that island, move it to region 0,0 where no islands spawn.

**Comment by DeltaVetal26** [comment]
I'm using the latest version of the plugin. The bottom line is that being on the island, I prescribe the / is reset command. Restart of the island occurs, but does not move me anywhere. And the things that were in the chests fall out and do not disappear. I really need that things be deleted, like the contents of the inventory. This is the essence of the ticket.

**Comment by Mohron** [comment]
Latest is not a version. The fact that you did not move in the video you recorded after starting a reset is a problem because when the server makes massive changes that fast it can't keep the client synced leaving ghost blocks and items behind. I'll deal with chests/inventory carrying blocks in my next update differently though.

**Comment by DeltaVetal26** [comment]
To be precise, I'm using version 0.21.0-BETA. The thing is that I'm interested in cleaning things that fall out of the chests. It would be desirable, that all things falling out from chests and other blocks, were automatically deleted. When can I expect an update? For me, this plugin is very important. Thank you.
