### ISSUE TITLE
[Question] Got any plans of updating to 1.12 soon?

### ISSUE THREAD

**Issue by Tylerun** [DevOnTheRocks/SkyClaims#47]
As Said by the subject got any plans?

**Comment by Mohron** [comment]
Have you tried using the current release version? It should run with 1.10.2+ If you are experiencing issues with SkyClaims on Sponge 1.12, I'll need to know the specifics in order to address them.

**Comment by Mohron** [comment]
Completed in b9bd67bc57f1bae4c5c8c573532a0dbb3209d5a3
