### ISSUE TITLE
Can't create islands

### ISSUE THREAD

**Issue by WorseWaif** [DevOnTheRocks/SkyClaims#48]
### Version:

- **Sponge:**  spongeforge-1.11.2-2393-6.1.0-BETA-2499 
- **SkyClaims:**  SkyClaims-0.22.0-BETA
- **GriefPrevention:**  griefprevention-1.11.2-4.1.0.317 
- **Permissions:**  LuckPerms-Sponge-3.2.61

### Expected Behavior:

Creating islands

### Actual Behavior:

I get an error and the island isnt created, the console states
[Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'is create' for source EntityPlayerMP['WorseWaif'/85, l='SkyIslands', x=64.60, y=114.37, z=3.29]: me.ryanhamshire.griefprevention.api.claim.Claim$Builder.cuboid(Z)Lme/ryanhamshire/griefprevention/api/claim/Claim$Builder;

### Steps To Reproduce:

I just go into the void world I created, and type /is create

**Comment by Mohron** [comment]
@WorseWaif Complete the top section of the Template... Pretty sure you're trying to use an unsupported version of GP.

**Comment by WorseWaif** [comment]
the heck!? I did fill that out, heck i copied and pasted the names of the jar files -_-. ok lets do this again

spongeforge-1.11.2-2393-6.1.0-BETA-2499
SkyClaims-0.22.0-BETA
griefprevention-1.11.2-4.1.0.323
LuckPerms-Sponge-3.2.65

I just checked again to make sure each one was the latest version, and tested again to make sure I got the same result, which I did.

**Comment by Mohron** [comment]
Did you leave them in the comments? lol that hides that text :D
Ya, I don't have a release for GP 4.X.0.XXX builds yet. The GP API had lots of changes. I'll get a new build out soon.

**Comment by WorseWaif** [comment]
ah, well I suppose its pretty obvious I'm completely clueless about this stuff haha. Awesome, thanks for the help!

**Comment by Mohron** [comment]
https://github.com/DevOnTheRocks/SkyClaims/releases/tag/beta-23
