### ISSUE TITLE
Request - store inventory when going to/from skyblock

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [DevOnTheRocks/SkyClaims#49]
Be nice to store a players inv/armour when they goto their island, so they dont take all the tools etc with them from a diff world in a multi world environment...
Then return the inv and store their skyblock inv.

This way the skyblock is a try mini game within the server.
I know there is a plugin to store inv in mysql on sponge ore, but be nice to incorporate it into the plugin.

**Comment by Mohron** [comment]
Sounds like you need an inventory management plugin. Your skyblock world should be separate of other worlds so you should be able to use a plugin like project inventories to accomplish the setup you're looking for. 

**Bottom Line:** _At this time, Inventory Management will not be added to SkyClaims.  If you want multiple Inventory support, a plugin designed for that purpose must be used._

**Comment by fusionmc-evilscoop** [comment]
ahh fantastic, didnt know that plugin worked....
cheers
