### ISSUE TITLE
Allow unsafe teleport when fly/creative is enabled

### ISSUE THREAD

**Issue by Slind14** [DevOnTheRocks/SkyClaims#5]

**Comment by Mohron** [comment]
@Slind14 are people not getting the option to force teleport? It should be giving them the option in their chat.

**Comment by Slind14** [comment]
Its telling me that it is not safe. Unless I don't understand the message, no.

**Comment by Mohron** [comment]
It should be sending 2 messages. See https://github.com/Mohron/SkyClaims/blob/development/src/main/java/net/mohron/skyclaims/util/CommandUtil.java#L25

Edit: Actually it should be a single message.

**Comment by Mohron** [comment]
I see how it's not obvious where to click now. I will fix it.

**Comment by Mohron** [comment]
Fixed via 9924ff33a2ed8d1709cebfba4e02ce1e94847bfd
