### ISSUE TITLE
EXCEEDS_MAX_SIZE_X when trying to create new island

### ISSUE THREAD

**Issue by kaal-1** [DevOnTheRocks/SkyClaims#50]
### Version:
- **Sponge:** 1.10.2-2281-5.2.0-BETA-2510
- **SkyClaims:** SkyClaims-0.23.0-BETA
- **GriefPrevention:** griefprevention-1.10.2-4.0.0.328
- **Permissions:** LuckPerms-Sponge-3.2.21

When a new user tries to do /is create this error is thrown:
![](https://image.prntscr.com/image/R3wiT-jFSc6Q5cmZU36Gfw.png)

I have the island size set to 256 in skyclaims config. It started happening after updating to the latest version.

**Comment by kaal-1** [comment]
Ok, so apparently there is an option in GriefPrevention (https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Options) that limits the max size of the claims. I have no idea why it worked before and not now, but I changed it.

Now I get this:
![](https://image.prntscr.com/image/EkuK1KKRTC6NXfRagTxojQ.png)

And this on the server console: https://hastebin.com/womecucoqa.rb

**Comment by Mohron** [comment]
@kaal-1 Can you upload the entire log to Gist?

**Comment by kaal-1** [comment]
Can I get your discord/email or something else to send the log to? I think it contains some sensitive information.

**Comment by Mohron** [comment]
Both of these issues have to be solved on GP's side. See the linked tickets for more info.

**Comment by Mohron** [comment]
Fixed your first issue via 1558474.

**Comment by Mohron** [comment]
Fixed 402a495
