### ISSUE TITLE
Can't create an Island without lp * permission, and can go outside the island boundary.

### ISSUE THREAD

**Issue by WorseWaif** [DevOnTheRocks/SkyClaims#51]
### Version:

- **Sponge:** spongeforge-1.11.2-2393-6.1.0-BETA-2499
- **SkyClaims:** SkyClaims-0.23.0-BETA
- **GriefPrevention:** griefprevention-1.11.2-4.1.0.323
- **Permissions:** LuckPerms-Sponge-3.2.65

### Expected Behavior:

I finally managed to get it working (creating islands with the right schematic in the right world, I guess it doesnt like capital letters in the names of the worlds, and the schematics are different than world edit so i had to paste the world edit schematic then use the golden axe to save it as a skyclaims schematic instead of just dropping the file into the folder)

### Actual Behavior:

I noticed that even though the wilderness is set up to prevent entering,and the placing/breaking of blocks, I could still go outside my island's boundaries and place/break blocks. I figured it might be due to having * permissions for lp, so I removed my permissions, but I could still could do those things. I then assumed it was because I created the is as an admin, so I deleted my island, made a testers group, added myself to it, and gave the group the permission to do /is create. But without * permissions I cant make an island. I tried giving the group permissions for world tp, gp claim create, spawn and set spawn, but I got the same error.

### Steps To Reproduce:

remove lp permission * and do /is create
with permission * and an island, build outside the boundaries with the world config set to no entering, building, or placing blocks in the wilderness..

**Comment by WorseWaif** [comment]
forgot to post this, this is that i get in the console when I try /is create without lp permission *
[Server] INFO java.lang.NullPointerException
[Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'is create' for source EntityPlayerMP['WorseWaif'/204, l='Main_Hub', x=242.79, y=64.00, z=80.46]: null

**Comment by Mohron** [comment]
The Permission bug has been reported to GP. If you can reproduce the flag bug with only the latest Sponge, GP, & LP, report it to GP's github to get it fixed.

**Comment by Mohron** [comment]
Fixed in 402a495
