### ISSUE TITLE
On Island Create getting Error in chat not in console. 

### ISSUE THREAD

**Issue by Tylerun** [DevOnTheRocks/SkyClaims#52]
http://prntscr.com/g8eeuu

I have no idea whats going wrong here. Need anything to explain let me know.

**Comment by Mohron** [comment]
Please use the provided Issue Template. The screenshot you provided does not give me enough information to debug your issue. I'll reopen this once you provide the information I need.

**Comment by Mohron** [comment]
If you don't update your ticket, there's no way I can help you.

**Comment by Tylerun** [comment]
You closed it and I resolved the issur myself thanks though sorry didnt update this

**Comment by Mohron** [comment]
I'm glad you found a fix. 👍
