### ISSUE TITLE
Payload may not be larger than x bytes on /is spawn

### ISSUE THREAD

**Issue by kaal-1** [DevOnTheRocks/SkyClaims#53]
- **Sponge:** spongeforge-1.10.2-2281-5.2.0-BETA-2591
- **SkyClaims:** SkyClaims-0.23.1-S5.1-BETA
- **GriefPrevention:** griefprevention-1.10.2-4.0.0.339
- **Permissions:** LuckPerms-Sponge-3.2.21

When I use /is spawn to go to a big island, I get disconnected with the following error.
![](https://cdn.discordapp.com/attachments/336981557497561091/351036910170406922/Sem_Titulo.png)

**Comment by Mohron** [comment]
SkyClaims doesn't have anything to do with sending packets and is unlikely the cause of this bug. Unless you can provide exact steps to reproduce, I won't be able to look into this further.  `Is spawn` just uses Sponge's built in teleportation helper anyways.
https://github.com/DevOnTheRocks/SkyClaims/blob/sponge/api-5/src/main/java/net/mohron/skyclaims/util/CommandUtil.java#L60

**Comment by Mohron** [comment]
No response in 2 weeks. Considering this issue resolved.
