### ISSUE TITLE
Not working on API 7 (1.12)

### ISSUE THREAD

**Issue by kaal-1** [DevOnTheRocks/SkyClaims#54]
- **Sponge:** spongeforge-1.12.1-2444-7.0.0-BETA-2602
- **SkyClaims:** SkyClaims-0.23.1-S7.0-BETA
- **GriefPrevention:** griefprevention-1.12.1-4.2.0.387
- **Permissions:** LuckPerms-Sponge-3.2.60

When I try to use the /is create command I get this on the console: https://hastebin.com/ajerumizax.vbs
And the island is not generated.

**Comment by DrZoddiak** [comment]
Update SkyClaims to latest and re-test
https://ore.spongepowered.org/Mohron/SkyClaims/versions

**Comment by Mohron** [comment]
Please do as @DrZoddiak said and try the latest version for S7.0. API 7 is constantly changing so I won't be supporting any outdated builds for it.

**Comment by phit** [comment]
latest rls on github is 23.1 🤔

**Comment by Mohron** [comment]
@phit Github has never been my primary place for releases. All my documentation points to ORE.

**Comment by kaal-1** [comment]
Same thing using the latest version.

**Comment by Mohron** [comment]
Unable to reproduce:
- Sponge: spongeforge-1.12.1-2444-7.0.0-BETA-2602
- SkyClaims: SkyClaims-0.24.0-S7.0-BETA
- GriefPrevention: 1.12.1-4.2.0.393
- Permissions: LuckPerms-Sponge-3.3.15

Update Sponge and your plugins and make sure you're not using a WorldEdit Schematic.

**Comment by kaal-1** [comment]
Aren't you supposed to use a worldedit schematic? well that's the problem then lol
How do I create the schematic without worldedit?

**Comment by phit** [comment]
https://github.com/DevOnTheRocks/SkyClaims/wiki/Schematics
