### ISSUE TITLE
How to share the island with friends to play together？

### ISSUE THREAD

**Issue by Sssssti** [DevOnTheRocks/SkyClaims#55]
How to share the island with friends to play together？
I only konw use /pt can share.But don't kown Permission node.

**Comment by Mohron** [comment]
@Sssssti  https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Permissions
Member - /trust `griefprevention.user.claim.command.trust.build`
Manage - /permissiontrust `griefprevention.user.claim.command.trust.permission`

**Comment by Mohron** [comment]
No response in 5 days, considering this solved.
