### ISSUE TITLE
SkyClaims Incompatable with Latest Sponge API 7 Changes

### ISSUE THREAD

**Issue by ghost** [DevOnTheRocks/SkyClaims#58]
http://prntscr.com/gkxsv9

It seems like this is happening with all Skyclaims commands but /is info and I am running the latest 1.12.1 Spongeapi with the Latest Griefprevention and Luckperms as well.

Any ideas what might be causing this

**Comment by Mohron** [comment]
This is due to the Sponge API Cause and Context refactor. https://github.com/SpongePowered/SpongeAPI/commit/9aeb46721b8bcaa45c96e1b73ef0ddd18c4d78ff

Awaiting a fix for https://github.com/NucleusPowered/Nucleus/issues/934 before a new SkyClaims release is made.

**Comment by Mohron** [comment]
This fix will be released with #59, probably sometime this weekend.

**Comment by Mohron** [comment]
https://ore.spongepowered.org/Mohron/SkyClaims/versions/0.25.0-S7.0-BETA
