### ISSUE TITLE
Add Plugin License

### ISSUE THREAD

**Issue by Mohron** [DevOnTheRocks/SkyClaims#6]
@cossacksman and myself have decided on a license for this project, [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).

@Slind14 @minecreatr because you both have code merged into this project, please indicate here whether or not you approve us merging your works under this license. If not all of your contributions will have to be removed.

**Comment by Slind14** [comment]
I don't mind.

**Comment by minecreatr** [comment]
Im fine with it.

**Comment by Mohron** [comment]
Okay guess we picked a license not really designed for software so lets try this again...
[GNU GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)
@Slind14 @minecreatr

**Comment by minecreatr** [comment]
Ok, I am fine with this license.

**Comment by Slind14** [comment]
of course, fine with me.

**Comment by Mohron** [comment]
Thanks for confirmation!
