### ISSUE TITLE
All islands deleted. No islands on /is list

### ISSUE THREAD

**Issue by NukeJS** [DevOnTheRocks/SkyClaims#61]
Yo,

Yesterday all of my islands have been removed from the /is list. When i'm on my island it says You must be on an island to see the information when using /is info. And i was on my is

**Comment by DrZoddiak** [comment]
- **Sponge:** <-- Sponge Forge/Vanilla Version -->
- **SkyClaims:** <-- SkyClaims Version -->
- **GriefPrevention:** <-- GriefPrevention Version -->
- **Permissions:** <-- Permissions Plugin Name & Version -->
Please provide that information
Also was this after an update or just randomly?

**Comment by Mohron** [comment]
Use the issue template or I can't help you. None of the information that's needed to debug this issue was provided.

**Comment by Mohron** [comment]
No response recieved in 7 days.
