### ISSUE TITLE
NoSuchMethodError 1.12.2

### ISSUE THREAD

**Issue by ziceptor** [DevOnTheRocks/SkyClaims#62]
forge-1.12.2-14.23.0.2486-universal.jar
spongeforge-1.12.2-2486-7.0.0-BETA-2646.jar
SkyClaims-0.24.0-S7.0-BETA.jar

https://gist.github.com/ziceptor/249d042db3cf1ccf96d04e4cc8793968

**Comment by Mohron** [comment]
Duplicate of #58
