### ISSUE TITLE
Add Configurable Teleport Location

### ISSUE THREAD

**Issue by SubtypeZero** [DevOnTheRocks/SkyClaims#66]
Mostly for advanced users, this option would allow server owners to change the location that players are sent to after being kicked from islands. My server uses a separate world for the primary spawn location (/spawn takes you to the "spawn" world's spawn instead of the current world's spawn). This allows us to change some settings specifically for that world, such as preventing day/night cycles, which would not be an option if our spawn was located in the main world. To prevent players from getting stuck or wondering where they have been moved to, I would like the ability to override the default location and send players to the spawn location of a different world.

**Comment by Mohron** [comment]
I'll probably just add a spawn-world config setting that you can use to override the default behavior of using the same world's spawn. If that world is not loaded or does not exist, I will still send them to the Island world's spawn point.
