### ISSUE TITLE
/is commands not recognized

### ISSUE THREAD

**Issue by Muzixs** [DevOnTheRocks/SkyClaims#72]
### Version:

- **Sponge:** 1.10.2-2477-5.2.0-BETA-2691
- **SkyClaims:** 0.25.1-S5.1-BETA
- **GriefPrevention:** 1.10.2-4.0.1.472
- **Permissions:** LuckPerms 3.4.20
- **Modpack:** Sky Factory 3 3.0.15

### Expected Behavior: 

Expected /is commands to function as described.

### Actual Behavior: 
Plugin does not appear to recognize the /is commands as defined on the [Sky Claims wiki](https://devontherocks.github.io/SkyClaims/#/commands?id=integrated-commands).

Additionally, it [outputs this given error](https://pastebin.com/bgKeak7c), not sure its related. Full log can be downloaded from the [following link](https://www.dropbox.com/s/7luz3wgix977b6a/fml-server-latest.log?dl=0).

### Steps To Reproduce:

No steps other then setting the server up with the plugins and Sponge listed in Version.

**Comment by Muzixs** [comment]
Update. I assumed the plugin wasn't loading base off the inability to use the /is command but after try /scversion I can see its loaded in but still gives the error posted before. The /is commands do not appear to be working.

Are there to divisions of commands for this plugin?

**Comment by SubtypeZero** [comment]
It looks like the full log is no longer available.

**Comment by Muzixs** [comment]
Well shoot. [Here's another link.](https://www.dropbox.com/s/7luz3wgix977b6a/fml-server-latest.log?dl=0)

**Comment by Mohron** [comment]
GP API made a breaking change. Your GP version is too new for that build

**Comment by Muzixs** [comment]
I see. 

Looks like 4.0.0.433 works but any GP version past 4.0.0 wont work for now. Thanks!
