### ISSUE TITLE
Problems expanding island [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [DevOnTheRocks/SkyClaims#79]
### Version:

- **Sponge:** spongeforge-1.10.2-2477-5.2.0-BETA-2691.jar
- **SkyClaims:** SkyClaims-0.26.0-S5.1-BETA.jar
- **GriefPrevention:** griefprevention-1.10.2-4.0.1.474.jar
- **Permissions:** LuckPerms-Sponge-3.4.20.jar

### Expected Behavior:

The /is expand 1 command should increase the size of the island and the protection

### Actual Behavior:

I need help to execute the command "/is expand 1"
The size of the initial islands is 6x6 chunks and the maximum to expand is 20x20 chunks.
But when executing the command "/is expand 1" the following message appears in the chat 
![screenshot_3](https://user-images.githubusercontent.com/13698597/31642571-409d6d9e-b2b1-11e7-8d89-84fbb46c1502.png)

and when I press "yes" it appears again without increasing the size of island, therefore, my island is still 6x6 chunks.
I have already assigned the permissions and limit to each group, attached images.
I hope you can help me, thank you!

![screenshot_4](https://user-images.githubusercontent.com/13698597/31642587-53131122-b2b1-11e7-8b43-6bb755c310af.png)
![screenshot_5](https://user-images.githubusercontent.com/13698597/31642590-580910e6-b2b1-11e7-8453-c4d8050efc59.png)

### Steps To Reproduce:

Run the command "/is expand 1"

**Comment by Mohron** [comment]
Odd. I'll take a look at this later today.

**Comment by Mohron** [comment]
Ha ha... https://github.com/DevOnTheRocks/SkyClaims/blob/sponge/api-5/src/main/java/net/mohron/skyclaims/command/user/CommandExpand.java#L107 what was I smoking!?!?

Still doesn't really make much sense since you provided a number >= 1...

**Comment by HeberonYT** [comment]
Sorry, I do not understand English.
I am doing something wrong?
Should I expect an update?
Regards!

**Comment by Mohron** [comment]
It's a bug and I haven't had any luck finding the cause/fix yet...
