### ISSUE TITLE
Island creation broken on fresh server

### ISSUE THREAD

**Issue by phit** [DevOnTheRocks/SkyClaims#8]
compiled from 0a9e7c3
http://vpaste.net/eEh69

**Comment by Mohron** [comment]
@phit this is what happens when you compile bleeding :P but on another note this should be fixed via  03fa243d9701c2d20cc7fd56f5109219a48b7bfe

**Comment by phit** [comment]
it was fixed here [0ad3acf](https://github.com/Mohron/SkyClaims/commit/0ad3acf6e6eb7cb9e714602f8fda881fe90b075f#diff-49d02745bab766439ab6aec1cd7596c1R45), but yeah it's fixed

**Comment by Mohron** [comment]
Trust me, every claim will overlap until 03fa243

**Comment by phit** [comment]
well the issue here wasn't that, but I couldn't even make a first island :P
