### ISSUE TITLE
NoSuchElementException: No value present

### ISSUE THREAD

**Issue by ziceptor** [DevOnTheRocks/SkyClaims#82]
https://gist.github.com/ziceptor/6c4b56cf629a60c37e6536f838c9e28d

forge-1.12.2-14.23.0.2503-universal.jar
spongeforge-1.12.2-2503-7.0.0-BETA-2720.jar
SkyClaims-0.26.0-S7.0-BETA.jar

**Comment by SubtypeZero** [comment]
Looks like your config file is messed up, is there some bad formatting?

**Comment by SubtypeZero** [comment]
Can you supply your log file?

**Comment by Mohron** [comment]
Known issue fixed in 6b9669c2a4fbe1fea03c7394711828d306f28461. Just grab a dev build because there hasn't been a release.

https://ci.devonthe.rocks/repository/download/SkyClaims_Build/34:id/build/libs/SkyClaims-0.26.1-S7.0-SNAPSHOT%2B34.jar

**Comment by ziceptor** [comment]
Artifact does not exist: 'build/libs/SkyClaims-0.26.1-S7.0-SNAPSHOT 34.jar' in build #34 {build id=34, buildTypeId=SkyClaims_Build}

**Comment by ziceptor** [comment]
guest login
