### ISSUE TITLE
Problem with spawn permission [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [DevOnTheRocks/SkyClaims#83]
### Version:

- **Sponge:** spongeforge-1.10.2-2477-5.2.0-BETA-2698.jar
- **SkyClaims:** SkyClaims-0.26.0-S5.1-BETA.jar
- **GriefPrevention:** griefprevention-1.10.2-4.0.1.474.jar
- **Permissions:** LuckPerms-Sponge-3.4.20.jar

### Expected Behavior:

The "skyclaims.command.spawn" permission should allow you to go to your own island, but it should prevent you from visiting the islands of other users.

### Actual Behavior:

Currently the permission "skyclaims.command.spawn" allows all users to visit all the islands.

### Steps To Reproduce:

1-Grant the "skyclaims.command.spawn" permission to the default group.
2-Use command /is spawn <user>

**Comment by SubtypeZero** [comment]
Right, that permission makes it possible for players to spawn at any island which they have access to. For them to have access, the island would either need to be public (unlocked), they would need to be a member of the island, or they would need to be the owner of that island. There's a separate set of permissions for changing which islands show up in `/is list`, which you can also configure to your liking. If you don't want islands to be unlocked, then I'd suggest making it so islands are locked by default and remove the ability for players to toggle the locked/unlocked status of their island.

**Comment by Mohron** [comment]
As Zero said, `skyclaims.command.spawn` allow use of `/is spawn` which then performs additional permission checks:
- Target Island unlocked = ALLOW
- Member/Manager/Owner of the target Island = ALLOW
- Has `skyclaims.admin.spawn` - ALLOW
- DENY all others
