### ISSUE TITLE
SkyClaims /is spawn bug?

### ISSUE THREAD

**Issue by LordFabian33** [DevOnTheRocks/SkyClaims#87]
### Version:

- **Sponge:** 1.10.2-2477-5.2.0-beta-2793 
- **SkyClaims:**  0.26.1-S5.1-beta 
- **GriefPrevention:** 1.10.2-4.0.1.5.0.7 
- **Permissions:** luckperms-Sponge-4.0.97 

### Expected Behavior:

I had a player invite another player to there island and when they did /is spawn to go to the island they were invited to it said you can only do this command if you belong to an island but when they did /is info both players are on the island How do i fix this issue?

### Actual Behavior:

 /is spawn to an island you are invite to not working ( You can only do this command if you belong to an island. 

### Steps To Reproduce:

 Not sure how to fix

**Comment by SubtypeZero** [comment]
Please update to the latest version for support, releases can be found [here](https://ore.spongepowered.org/Mohron/SkyClaims/versions).

**Comment by LordFabian33** [comment]
Would i also have to delete the config folder for the older version of skyclaims?

**Comment by Mohron** [comment]
No, the config will update on its own

**Comment by Mohron** [comment]
@LordFabian33 are you still having an issue?

**Comment by Mohron** [comment]
Closing due to no response from user in 8 days. Reopen if the same problem persists.
