### ISSUE TITLE
Skyclaims - Islands can be freely deleted by anyone

### ISSUE THREAD

**Issue by tolly765** [DevOnTheRocks/SkyClaims#90]
### Version: 

- **Sponge:**  1.10.2-2477-5.2.0-BETA-2731
- **SkyClaims:**  0.27.1-S5.1-BETA (Latest API5 version as of this issue)
- **GriefPrevention:**  1.10.2-4.0.1.535
- **Permissions:**  LuckPerms 4.0.130

### Expected Behavior:

When using /is info, you should not be able to use the delete button on other people's islands (see picture: http://prntscr.com/ioazbw). This should only work on the person's own island or for people with the admin command permissions.

### Actual Behavior:

Upon using /is info, the island in question can show up in the chat with an option to delete the island. Upon confirming this, the island is deleted completely with no trace. There is no warning stating that there are insufficient privileges and anyone can do it. 
Gist on LP verbose when performing the actions below: https://gist.github.com/anonymous/0aa997b9bb35b5c98707882ad1523d1c

### Steps To Reproduce:

1) Find an island owned by someone else
2) Do /is info on the island.
3) Click Delete.
4) Click YES.
5) Say goodbye to the island.

**Comment by Mohron** [comment]
d5701823f8ab179b0db7fadbfd143582111a4965

**Comment by tolly765** [comment]
Thanks for the quick fix! 👍
