### ISSUE TITLE
a crash report 

### ISSUE THREAD

**Issue by subtank** [DevOnTheRocks/SkyClaims#91]
[crash-2018-04-10_08.11.14-server.txt](https://github.com/DevOnTheRocks/SkyClaims/files/1892513/crash-2018-04-10_08.11.14-server.txt)

**Comment by Mohron** [comment]
Have you recently added any new plugins? Something is conflicting with the metrics class

**Comment by subtank** [comment]
no,just as the list in file end

**Comment by Mohron** [comment]
Can you upload your metrics config?

**Comment by subtank** [comment]
where can i find it

**Comment by Mohron** [comment]
Metrics folder where the rest of your sponge configs are

**Comment by subtank** [comment]
this one?

**Comment by subtank** [comment]
[config.zip](https://github.com/DevOnTheRocks/SkyClaims/files/1892585/config.zip)

**Comment by Mohron** [comment]
Try going into your bstats folder and disabling metrics.

**Comment by Mohron** [comment]
Closing this issue since there has been no more activity for a couple months.
