### ISSUE TITLE
[Suggestion]Limit the maximum number of players an island may contain

### ISSUE THREAD

**Issue by Tollainmear** [DevOnTheRocks/SkyClaims#96]
Hi Mohron, I like this plugin so much, and it would be better if SkyClaims could limit the maximum number of players an island may contain, maybe we could achieve that by checking the owner permission?

**Comment by Tollainmear** [comment]
Wow, Mohron! that's amazing!
Is this what you were planning to do?！Your efficiency is too shocking！🌹

**Comment by Mohron** [comment]
I had thought about it before but never started it. Either way, I knew it would be an easy addition.

**Comment by Tollainmear** [comment]
I think this issue should be closed after 4f18a77b0682518facd20557b2fbbda6396a991c, but it wasn't.

BTW, when can we get the release whit this feature?

**Comment by Mohron** [comment]
That's because the feature was implemented on a separate branch, along with all the other upcoming changes for the next release. There is no ETA on the next release due to the shear amount of changes.

**Comment by Tollainmear** [comment]
Hi Mohron, I have compiled the source code in the branch named `feature/schematic-data`, and it seems like have a bug, I'm not good at describing in English, but I'll try my best:

- step 1: we set the meta `skyclaims.max-teammates` for default group as `1`
- step 2: the island owner invite two player at a time(the first player won't reply the invitation before the second invitation was sent)
- step 3:(make sure these two player both receive the invitation) the second player could accept the invitation after the first player has accepted, that means these two player was both invited to the island successfully, and the island member amount now was > the limit `1`

and if the invitation was sent while the team-mate amount was above(or equal) the limitation, the plugin works well, so if we rejudge the condition on player accept the invitation might be better.

**Comment by Mohron** [comment]
The check just needs to happen in both places. Good catch.

**Comment by Mohron** [comment]
This feature is available in the pre-release.
