### ISSUE TITLE
The suggestion about permission control

### ISSUE THREAD

**Issue by MoeShimaKaze** [DevOnTheRocks/SkyClaims#97]
I have a suggestion
Can you add a limit on the number of orders to rebuild the empty island?
My server's player uses the reset island to brush the basics
I hope you can fix this problem, thanks

**Comment by SubtypeZero** [comment]
Are you asking for a cooldown?

**Comment by Mohron** [comment]
This really doesn't make sense. You're going to need to explain if you want anything to come of this.

**Comment by Mohron** [comment]
Closing due to no response.
