### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by LemADEC** [DevOnTheRocks/SkyClaims#99]
### Version:
- **Sponge:** 1.12.2-2705-7.1.0-BETA-3481
- **SkyClaims:** 0.27.2-S7.0-BETA
- **GriefPrevention:** 1.12.2-4.3.0.646
- **Permissions:** LuckPerms-Sponge-4.2.67build727

### Expected Behavior:
Server boot

### Actual Behavior:
First boot after adding the mod crashes the server.

https://gist.github.com/LemADEC/562bbe076f97831482f6232ee2ff64de

### Steps To Reproduce:
Create server, boot => ok
Add SkyClaims, boot => NOK
Reboot => ok

**Comment by Mohron** [comment]
First time installing SkyClaims on this server correct? It seems there was a problem with the DB first run. Can you send the entire log?

**Comment by LemADEC** [comment]
to be more specific, first boot was with sponge but no plugins, second boot was with all plugins including SkyClaims.

**Comment by LemADEC** [comment]
Here's the full log for that issue: https://gist.github.com/LemADEC/6a6c56a0119d75a7049da0f79c5e182f
All plugins were running with default configuration.

**Comment by Mohron** [comment]
`java.sql.SQLException: path to '/home/skyadventures/./config/skyclaims/data/skyclaims.db': '/home/skyadventures/./config/skyclaims' does not exist`  Some how skyclaims tryied to access the database file before the directory even existed :/

Could be a fluke or could be a bug, I'll have to investigate further.  But be assured that it was just a one time error.
